### ISSUE TITLE
Segmentation fault with VBO and point cloud with normal vectors

### ISSUE THREAD

**Issue by erwi** [cloudcompare/trunk#148]
Hi, I get a segmentation fault (CloudCompare terminates with error message "Segmentation fault") when VBO is turned on in display settings and the cloud contains normal vectors. I imagine this might be related to the recent VBO problems on Linux (issue #147), but occurs even after having applied the fix for it. 

This happens only when VBO is turned on *and* the displayed cloud contain surface normals. Everything works well with VBO on, but without surface normals. It doesn't matter whether the normals are loaded from a file or calculated in CloudCompare. The crash doesn't always seem to happen for very small point clouds with only a few thousand points or less. I have only tested this on Linux. 

Thanks.

**Comment by cloudcompare** [comment]
I believe it's fixed now
