### ISSUE TITLE
Compiling and starting under linux gives problems with X

### ISSUE THREAD

**Issue by mojovski** [cloudcompare/trunk#152]
After successfully compiled CC (wow!), the programm gives me an error on loading a mesh:

Xlib:  extension "NV-GLX" missing on display ":0".
X Error: BadRequest (invalid request code or no such operation) 1
  Extension:    153 (Uknown extension)
  Minor opcode: 187 (Unknown request)
  Resource id:  0x2c00015
[xcb] Too much data requested from _XRead
[xcb] This is most likely caused by a broken X extension library
[xcb] Aborting, sorry about that.
CloudCompare: ../../src/xcb_io.c:736: _XRead: Assertion `!xcb_xlib_too_much_data_requested' failed.
Aborted (core dumped)

However, this does not happen to all meshes.  :/
Do I have not enough memory on my graphic card?

**Comment by felixlaumon** [comment]
I got the same error running CC through remote X11 from Mac OS X El Captian Xquartz 2.7.8. The server has a NVdia Titan X. Turning off "Try to load clouds on GPU for faster display" works.

````
X Error: BadRequest (invalid request code or no such operation) 1
  Extension:    150 (Uknown extension)
  Minor opcode: 187 (Unknown request)
  Resource id:  0x60002b
[xcb] Too much data requested from _XRead
[xcb] This is most likely caused by a broken X extension library
[xcb] Aborting, sorry about that.
CloudCompare: ../../src/xcb_io.c:736: _XRead: Assertion `!xcb_xlib_too_much_data_requested' failed.
[1]    12262 abort      /usr/local/CloudCompare/CloudCompare person.pcd
````
