### ISSUE TITLE
Wrong coloring of imported point clouds

### ISSUE THREAD

**Issue by mwoehlke-kitware** [cloudcompare/trunk#161]
CC 1d0a14ea2c127b2d does not seem to be properly handling per-point cloud colors at all. (Indeed, when I see different colors at all, they seem to be based somehow on the cylindrical coordinates of the points, even though the color / scalar data are not at all of this nature.)

My "interesting" data is unfortunately private, but I can reproduce with just about anything. For example, I quickly hacked up a particle engine I wrote to dump to a .xyz file. Here's the result loaded in CloudCompare:

![cc](https://cloud.githubusercontent.com/assets/6474409/4095830/6c529f3c-2fb9-11e4-900f-3f55bc2323c2.png)

...and here's what it looks like in my particle engine program (i.e. what it's supposed to look like):

![frame](https://cloud.githubusercontent.com/assets/6474409/4095875/19706b22-2fba-11e4-8364-4931ec22fab8.png)

The positions are correct. The color I'm seeing does actually match the specified color of the first point in the .xyz file, but as you can see from the second image, there should be a rainbox of colors, not just blue. It seems that what is happening is that one color is being repeated for some large number of points, organized by some unknown logic (possibly raw ordering; since my "real" data comes from laser scanners, it makes sense that their raw ordering would fall into "cylindrical bins").

I'm happy to also provide the .xyz file on request. I'm on Fedora 20 x86_64 using the Free drivers for a "Radeon HD 6730M/6770M/7690M XT".

**Comment by cloudcompare** [comment]
This issue has never been reproduced.
