### ISSUE TITLE
2.6.0 - Normals not imported with FARO FLS or FARO project files

### ISSUE THREAD

**Issue by onitreb** [cloudcompare/trunk#173]
Great to see the FARO support in CC.

Currently, normals are not imported into cloud compare. Is this planned for the future? Or are normals not inside FLS/PROJ files?

**Comment by onitreb** [comment]
Is calculating normals with FARO scans a planned feature?

Or a feature to tell CC to computer normals after import?

**Comment by cloudcompare** [comment]
Oups, I forgot to add it to the Faro I/O filter (I added it to the DP I/O filter though).

I guess it will be for the next release then.

**Comment by onitreb** [comment]
Ah! Excellent.

**Comment by cloudcompare** [comment]
Just for the records: one can now computed clean normals with any gridded cloud (PTX, FARO, DP, etc.) thanks to the new 'grid structure' associated to these kind of cloud (see http://www.cloudcompare.org/doc/wiki/index.php?title=Normals%5CCompute)
