### ISSUE TITLE
2.6.0 64bit / Win 8.1 - crash when importing PTX - "yes" to "compute normals"

### ISSUE THREAD

**Issue by onitreb** [cloudcompare/trunk#174]
The application crashes when I select "Yes" or "yes to all" to compute normals.

PTX exported from FARO scene 5.3.3

Same PTX file successfully imports into CC 2.5.4.1 (where there is no dialog about computing normals).

**Comment by cloudcompare** [comment]
I believe this is not valid anymore as we changed to way gridded cloud normals are computed.
