### ISSUE TITLE
Mac 2.6.0 crash on making selection

### ISSUE THREAD

**Issue by pyscajor** [cloudcompare/trunk#191]
Holding Option then making a selection with the mouse causes CC to crash each time for me - with or without a model loaded. I'm using OS X 10.10.1 and this happens consistently even after rebooting. 

Does this happen to other Mac users?

**Comment by asmaloney** [comment]
I've recreated this.  Doesn't look to be Mac-specific, but I'll look into it...

**Comment by asmaloney** [comment]
Looks like Daniel fixed this in commit 0cf3fab1bced398908d7099335d19a480925d7f5 so it should be fixed in the next release.

**Comment by pyscajor** [comment]
Glad you could recreate it, and that it's been resolved. 

Many thanks.
