### ISSUE TITLE
Cannnot save in Ubuntu 14.10

### ISSUE THREAD

**Issue by yqueau** [cloudcompare/trunk#192]
Hello, 

First of all, congratulations for this excellent software, which I've been exploring with great pleasure for the last few days. 

Yet, I encountered a rather annoying issue : after registering two meshes, I am not able to save the project. If I try to save, the sofware closes and I get the following message in the console : 

CloudCompare: symbol lookup error: CloudCompare: undefined symbol: _ZN12FileIOFilter10SaveToFileEP9ccHObjectRK7QStringS2_

Which would tend to indicate a trouble in dynamic library linkage ? 

Some (useful ?) comments : 
_ laptop HP EliteBook 9570w, with Ubuntu 14.04
_ sources downloaded by cloning the git repo
_ compilation and installation with CMake went fine (no error message at all)
_ every tested function seems to work ok, apart from the "save" function
_ "save" works like a charm with the same project run under Windows Vista

This bug is quite annoying, since I need to recompute the registrations everytime I launch the software...

Thanks in advance for the help !
Yvain

**Comment by cloudcompare** [comment]
Hi,

I'm not a Linux guru but it's quite strange as it means that there's several versions of the dynamic library on your system (and that visibly the wrong one is used).

Have you compiled the 'INSTALL' project (with *make install*) and then updated the .so libraries locations (with *'sudo /sbin/ldconfig -v*)? Eventually you have to start the project from its installed location (/usr/local/CloudCompare by default I believe).

**Comment by yqueau** [comment]
Thanks a lot, it is fixed. Running the /usr/local/CloudCompare/CloudCompare indeed fixes the bug. After some search, I found that I had two versions installed, and that the CloudCompare command called the wrong binary. 

Actually, before getting the github sources, I had tried the basic "sudo apt-get install CloudCompare" installation : seems like this intalls a buggy version which cannot save the projects. So I removed this install ("sudo apt-get remove CloudCompare"), and set the new binary to the one created using CMake / Make, by adding a line "export PATH=/usr/local/CloudCompare:$PATH;" in the .bashrc file. I could equivalently have re-compiled using make install. 

Maybe you could add a comment in the CMake installation page of the wiki, recalling to dumbs like me that before compiling the sources, any previous version must be removed ("sudo apt-get remove CloudCompare"). 

Now it works like a charm ! 

Thanks a lot, 
Yvain

**Comment by cloudcompare** [comment]
I didn't know that you could install a CloudCompare package so easily on Ubuntu?! Does it come from Romain Janvier's repository (https://launchpad.net/~romain-janvier/+archive/ubuntu/cloudcompare)?

**Comment by yqueau** [comment]
Yes it does !

**Comment by cloudcompare** [comment]
Okay then it would be good to warn Romain about this.

Thaks for the feedback anyway,

Daniel

**Comment by ORNis** [comment]
Well it's strange, I will look at this tomorow. Thanks for the feedback.
