### ISSUE TITLE
Clarify options in poissonrecon dialog box

### ISSUE THREAD

**Issue by foobarbecue** [cloudcompare/trunk#193]
As discussed at http://www.danielgm.net/cc/forum/viewtopic.php?f=9&t=1126 , it's unclear what the difference between "octree depth" and "full depth" is, and in fact their tooltips are identical.

**Comment by cloudcompare** [comment]
Indeed, I've just read your message and corrected the tooltip for the 'full depth' parameter. I keep the PoissonRecon description though (*the depth beyond depth the octree will be adapted. At coarser depths, the octree will be complete...*).

And for what it means, let's continue the discussion on the forum ;)
