### ISSUE TITLE
Transformation option for command line ?

### ISSUE THREAD

**Issue by GerhardR** [cloudcompare/trunk#194]
Hi,

I am using CloudCompare to automate testing work flows for reconstruction applications. It's a great tool and having the command line interface is really a big plus for that. 

I would like to suggest to add a transformation option to the set of command line tools. For example something where a 4x4 transformation matrix is applied to an input cloud or mesh. This would make it very easy to script workflows where I know a fixed transformation between two clouds that I want to compare.

thanks,
  Gerhard

**Comment by cloudcompare** [comment]
Indeed. As we now have the possibility in the *Edit > Apply transformation* tool to import/export transformation matrices from/to simple text files (the 4 values of each row of the matrix per line) it would be easy to add a command line option to load and apply such a transformation.

It should be done soon ;)

**Comment by GerhardR** [comment]
Thanks, I was hoping that it would be quite easy :)

**Comment by cloudcompare** [comment]
Okay that's done (a new 'APPLY_TRANS' option will be available in the next version - see http://www.cloudcompare.org/doc/wiki/index.php5?title=CommandLine).

**Comment by GerhardR** [comment]
great, thanks a lot !
