### ISSUE TITLE
Opening STL mesh hangs at Tag Duplicated Vertices step

### ISSUE THREAD

**Issue by davidcanada** [cloudcompare/trunk#195]
Opening STL meshes is hanging at the Tag Duplicated Vertices step.  Nothing seems to happen, the progress bar stays at 0. 
CC Viewer has no issue opening the same STLs.
![cc mesh hang](https://cloud.githubusercontent.com/assets/7146244/5851569/999aa7d0-a1c6-11e4-9d5e-1fc5f5594c39.JPG)

**Comment by cloudcompare** [comment]
Indeed, this issue has been fixed in the latest beta release (2.6.1.beta). You can download it from the website (http://www.cloudcompare.org/).

And thanks for the feedback ;)
