### ISSUE TITLE
Multiple point cloud file save as text

### ISSUE THREAD

**Issue by ramassin** [cloudcompare/trunk#196]
In older version of CC it was possible to select multiple clouds :cloud: from the DB tree, clicking 'save', and save the result as a text file.
The software would ask for a base name and save all the files with progressive numerals appended 
(file_0001.txt, file_0002.txt ...) This was very useful.

This feature is no longer present, now the only options are .bin, e57, .pov

To my understanding the relevant code is in function doActionSaveFile in [mainwindow.cpp](https://github.com/cloudcompare/trunk/blob/master/qCC/mainwindow.cpp#L10416) but i couldn't be able to dig further.

**Comment by dgirardeau** [comment]
This issue has been fixed in the latest (beta) release. Can you test it again? (2.6.1.beta)

**Comment by ramassin** [comment]
Yes indeed, (2.6.1.beta) works well with this respect, sorry.
I think this can be closed then?

**Comment by dgirardeau** [comment]
No problem.
