### ISSUE TITLE
Null Bounding Box

### ISSUE THREAD

**Issue by 21nds** [cloudcompare/trunk#200]
When creating a LAS file in command mode (2.6.1 alpha)
"C:\tmp\CloudCompare_v2.6.1alpha\CloudCompare.exe -o C:\tmp\Proj_652.bin -C_Export_FMT LAS -SS Random 4000000"

The file completes successfully, and when opened in CC it opens and actually lists as having 4mil points, but it has an error:
Entity/DB has a null bounding-box! Can't zoom in...

and nothing is actually displayed.
The box dimensions show X:0  Y:0  Z:0

Hopefully it is a quick fix in the -SS algorithm.

**Comment by dgirardeau** [comment]
Indeed. There's a missing exclamation marks in the LAS output filter!

Thaks for the feedback. I'll update the online beta version asap.

**Comment by dgirardeau** [comment]
Okay the new version is online!
