### ISSUE TITLE
2.5 triangulation now on wrong plane

### ISSUE THREAD

**Issue by ramassin** [cloudcompare/trunk#202]
Hello, it seems to me that in the new beta (2.6.1b) with the introduction of the new cross-section generation, something has changed with respect to 2.5d delaunay triangulation.
The relevant commit should be [this](https://github.com/cloudcompare/trunk/commit/5a468980fbfaf6a20e25cf2972ad71b25fd74ee7#diff-3ec48d9116ded5c39c65da56be63f222R200)

The triangulation now happens on the Z-Y plane and not on the X-Y.

**Comment by dgirardeau** [comment]
Indeed but it has been fixed already:
https://github.com/cloudcompare/trunk/commit/d97942d263242cb36c15d062b9277f957053c896

Have you tested the very last version (online since yesterday evening ;)

**Comment by ramassin** [comment]
hah!
sorry for the inconvenience, and thanks as usual.

**Comment by dgirardeau** [comment]
No problem, I prefer false/old bugs being reported than real bugs running free ;)
