### ISSUE TITLE
glew vs qt5?

### ISSUE THREAD

**Issue by luca-penasa** [cloudcompare/trunk#205]
Compiling with QT5 is giving a lot of warnings about glew vs. qt... Is that normal?

```
[ 33%] Building CXX object libs/qCC_glWindow/CMakeFiles/QCC_GL_LIB.dir/ccGLWindow.cpp.o
In file included from /usr/include/qt5/QtGui/QtGui:32:0,
                 from /home/luca/Code/CloudCompare-mine-git/libs/qCC_glWindow/ccGLWindow.cpp:52:
/usr/include/qt5/QtGui/qopenglcontext.h:57:2: warning: #warning qopenglfunctions.h is not compatible with GLEW, GLEW defines will be undefined [-Wcpp]
 #warning qopenglfunctions.h is not compatible with GLEW, GLEW defines will be undefined
  ^
/usr/include/qt5/QtGui/qopenglcontext.h:58:2: warning: #warning To use GLEW with Qt, do not include <qopengl.h> or <QOpenGLFunctions> after glew.h [-Wcpp]
 #warning To use GLEW with Qt, do not include <qopengl.h> or <QOpenGLFunctions> after glew.h
  ^
In file included from /usr/include/qt5/QtGui/QtGui:52:0,
                 from /home/luca/Code/CloudCompare-mine-git/libs/qCC_glWindow/ccGLWindow.cpp:52:
/usr/include/qt5/QtGui/qopenglfunctions.h:51:2: warning: #warning qopenglfunctions.h is not compatible with GLEW, GLEW defines will be undefined [-Wcpp]
 #warning qopenglfunctions.h is not compatible with GLEW, GLEW defines will be undefined
  ^
/usr/include/qt5/QtGui/qopenglfunctions.h:52:2: warning: #warning To use GLEW with Qt, do not include <qopengl.h> or <QOpenGLFunctions> after glew.h [-Wcpp]
 #warning To use GLEW with Qt, do not include <qopengl.h> or <QOpenGLFunctions> after glew.h
```

**Comment by luca-penasa** [comment]
BTW I also had to add a dependency on Qt5PrintSupport in CMakeExternalLibs.cmake to make CC to qcustomplot to compile (it seems it needs it when running on qt5)

**Comment by dgirardeau** [comment]
That's funny, I don't have those issues on Windows and Travis doesn't complain for gcc/clang (https://travis-ci.org/cloudcompare/trunk).

What Qt version are you using?

**Comment by luca-penasa** [comment]
I am on an ubuntu derived distro which provides qt 5.2.1

**Comment by dgirardeau** [comment]
Hum I realize that Travis compiles with Qt4 (so it doesn't helps ;).

**Comment by luca-penasa** [comment]
I'll try with another setup whenever it is possible, just to be sure it is not something specific to this version of qt or my setup

**Comment by ORNis** [comment]
@luca-penasa  libqt4 is still present in Ubuntu's repo.
@dgirardeau I will try to build with QT4 and QT5 on travis

**Comment by luca-penasa** [comment]
thanks ORNis...  
In fact compiling with libqt4 as provided by ubuntu repos works ok!

**Comment by chrisidefix** [comment]
To answer the original question. Yes, it is normal that Qt complains about including GLEW headers, but it's not really anything to worry about too much. You can use GLEW and Qt5 together!

**Comment by luca-penasa** [comment]
thus I think its ok to close the issue :+1:
