### ISSUE TITLE
Compilation error + Fix

### ISSUE THREAD

**Issue by werterit3** [cloudcompare/trunk#206]
Hi, 

i had some issues compiling CloudCompare with Qt 5.4 MinGW 4.9.1 32-Bit under Windows 8.1 Professional. I got the error Message "g++.exe: error: /MANIFEST:NO: No such file or directory". This error occurs because the gcc does not support the flag "/MANIFEST:NO". In order to remove this bug line 109 in file "trunk/qCC/CMakeLists.txt" and line 108 in file "trunk/ccViewer/CMakeLists.txt" have to be encapsulated by "if (MSVC) ... endif()". 

![bugcc](https://cloud.githubusercontent.com/assets/11596568/6769596/dca050dc-d0a3-11e4-9785-c81b28e5aab0.jpg)

Additionally the "make install" command fails, because the libraries "libgcc" and "mingwm" are not found. The Problem with libgcc is, that i may have some postfixes (libgcc_s_dw2-1.dll). The mingwm.dll is a file I have not seen for a while. I think it might be outdated. Furthermore the libstdc++6.dll is required by newer versions of MinGW. Modifying file "trunk/CMakeInclude.cmake" solves the problem. 

![bugcc2](https://cloud.githubusercontent.com/assets/11596568/6769669/b79d7cae-d0a5-11e4-8854-db1edf05359a.jpg)

That solves all problems, but I am going to start some further investigations with some other Qt and MinGW combinations. 

Best regards!

**Comment by cloudcompare** [comment]
Indeed its been a long time since someone has tried to compile CC with mingw (must be with Code::Blocks 10.XX!).

Thanks for the fix

**Comment by cloudcompare** [comment]
Okay I've pushed the fix on the CleanMeshCutter branch (it should be merged with the main branch soon).
