### ISSUE TITLE
Wrong command line option -ENABLE_FARTHEST_REMOVAL in documentation

### ISSUE THREAD

**Issue by EinfachToll** [cloudcompare/trunk#207]
I don't know if this is the right place to bring this up, but there is a mistake in the documentation. Here: http://www.cloudcompare.org/doc/wiki/index.php?title=Command_line_mode instead of -ENABLE_FARTHEST_REMOVAL it must be -FARTHEST_REMOVAL.

**Comment by cloudcompare** [comment]
Indeed! Thanks for the feedback.
