### ISSUE TITLE
Support for stereoscopy?

### ISSUE THREAD

**Issue by foobarbecue** [cloudcompare/trunk#208]
It would be fantastic if cloudcompare added support for anaglyph and / or quadbuffer stereo. There appear to be no free pointcloud editing programs which are stereo capable. Is anyone working along these lines yet?

**Comment by cloudcompare** [comment]
Well there's an Oculus Rift plugin in preparation. But it's taking a looooong time ;)

**Comment by foobarbecue** [comment]
Rift, schmift. My Nvidia shutter glasses are plenty 3D!

**Comment by cloudcompare** [comment]
Well, the point is that the Rift also needs stereo display, so at least it will be integrated into CC graphical engine...

**Comment by foobarbecue** [comment]
Is there a branch somewhere I can look at with the work in progress for Rift? Do you know if it uses quad buffer?

**Comment by cloudcompare** [comment]
No branch yet (that's somewhere on my google drive). And I haven't decided yet of the way to render the stereo pairs (but as the Rift has a single screen, it may be sufficient to use standard double buffering).

**Comment by foobarbecue** [comment]
Ok. You might be interested to know that I've been testing the multiview stereo branch of Blender, and it works great with Nvidia stereo glasses on both GeForce cards and Quadro cards (even though NVIDIA support has denied this is possible in my emails to them). The quad buffer implementation in AgiSoft Photoscan, however, only works on the Quadro cards. I don't know what the difference is. Blender also has  a separate branch called blender-vr for Rift and similar.

**Comment by cloudcompare** [comment]
Interesting indeed!

**Comment by foobarbecue** [comment]
http://www.mtbs3d.com/phpbb/viewtopic.php?f=2&t=17077 so far has more info on GeForce quadbuffer than I've found anywhere else. After badgering NVIDIA about it, they upgraded my ticket to "level 2" and now they won't reply at all.

**Comment by cloudcompare** [comment]
A little update on this subject: CC now supports quad buffering rendering. It is used for the NVidia 3D Vision glasses for now.

But the Oculus Rift plugin is not far away now that the biggest work has been done!

**Comment by foobarbecue** [comment]
Glad to hear it! Can't figure out how to make the NVidia 3D Vision work though -- do I need to enable stereoscopy somewhere in CC?

**Comment by foobarbecue** [comment]
Ah, I found "full screen 3D view"

**Comment by cloudcompare** [comment]
Hi,

I guess you have followed the rules displayed in the 'stereo mode' dialog?
![image](https://cloud.githubusercontent.com/assets/2735509/13320536/04822f94-dbca-11e5-9086-66025dc55cbf.png)

**Comment by foobarbecue** [comment]
Sorry, I didn't know I had to click the "stereo mode" button! Works brilliantly now, thanks! (Quadro k600, ASUS PG278Q)
