### ISSUE TITLE
Version 2.6.1 Importing multiple pointclouds in Windows 7 64 bits strange behaviour

### ISSUE THREAD

**Issue by WillemvH** [cloudcompare/trunk#210]
When I open multiple .laz or .las files in CloudCompare 2.6.1 64 bits, two strrange things happen:
- The application loses focus and moves to the background. Only the pop up is visible
- Yes to all doesn't work. I have to confirm for every cloud again.

Version 2.5.5.2 64 bits worked fine.

Willem

**Comment by cloudcompare** [comment]
Indeed,

The focus issue seem to appear mainly on Windows 8 (can you confirm?). It may also be an issue with Qt 5.4 (not clear about that).

And the 'Yes to all' bug is known (and should be fixed in the next version ;).

Thanks for the feedback anyway!

**Comment by WillemvH** [comment]
I am using CloudCompare on a Windows 7 64 bits Professional version. So, not only on Windows 8.

Best regards,
Willemh



________________________________

**Comment by cloudcompare** [comment]
Okay, I found the culprit (the progress dialog was behaving strangely since Qt 5.4 due to 'incompatible' flags we were using with the older versions of Qt). This issue will therefore be fixed in the next release.

**Comment by KAMI911** [comment]
I faced with this problem. When the next version will be released?

**Comment by cloudcompare** [comment]
You'll find the (fresh) beta version here:
http://www.cloudcompare.org/release/CloudCompare_v2.6.2.beta_bin_x64.zip

I'm afraid the official version won't be available before the summer vacations ;)
