### ISSUE TITLE
Geotiff import does not handle raster rotations

### ISSUE THREAD

**Issue by ramassin** [cloudcompare/trunk#213]
I tried importing a geotiff with rotation and it failed to rotate.
I dug a bit in the code and found that the values are correctly read at [RasterGridFilter](https://github.com/cloudcompare/trunk/blob/master/libs/qCC_io/RasterGridFilter.cpp#L80-88)

Unfortunately the rotation is not applied at [Y coord](https://github.com/cloudcompare/trunk/blob/master/libs/qCC_io/RasterGridFilter.cpp#L116) and  [X coord](https://github.com/cloudcompare/trunk/blob/master/libs/qCC_io/RasterGridFilter.cpp#L122) 

the code should follow GDAL suggestion that is 
```c++
   Xp = padfTransform[0] + P*padfTransform[1] + L*padfTransform[2];
   Yp = padfTransform[3] + P*padfTransform[4] + L*padfTransform[5];
```

it seems to me pretty straightforward to implement.
To test it it's enough to load a geotiff that has the accompanying tfw set to have non-null 2nd and 3d component, as in
```
-0.005191
0.008547
0.008547
0.005191
66666.410
66666.120
```

[link to GDAL reference](http://www.gdal.org/classGDALDataset.html#af9593cc241e7d140f5f3c4798a43a668)

**Comment by cloudcompare** [comment]
Thanks for spotting this.

I can see that on lines 116 and 122 we do apply the transformation (at least partly). However there may be an error as we use transform[5] for 'y' (instead of transform[4] that would be more logical and more consistent with the GDAL example). And I'm not sure what 'L' is the GDAL example by the way?

Can you send me your rotated raster? It will be easier to debug all this.

**Comment by ramassin** [comment]
L should be the raster line (that is the Y coordinate)

> Fetches the coefficients for transforming between pixel/line (P,L) raster space, and projection coordinates (Xp,Yp) space.

also from [here](http://www.remotesensing.org/geotiff/faq.html)
>Xgeo = E + Xpixel * A + Ypixel * C
Ygeo = F + Ypixel * D + Xpixel * B

**Comment by ramassin** [comment]
I think it should basically just become like this.  (untested)

```c++
//create blank raster 'grid'
{
	double z = 0.0 /*+ Pshift.z*/;
	for (int j=0; j<rasterY; ++j)
	{
	    for (int i=0; i<rasterX; ++i)
	    {
	    double x = adfGeoTransform[0] + static_cast<double>(i) * adfGeoTransform[1] +static_cast<double>(j) * adfGeoTransform[2]+ Pshift.x;
	    double y = adfGeoTransform[3] +  static_cast<double>(i) * adfGeoTransform[4] + static_cast<double>(j) * adfGeoTransform[5] + Pshift.y;
	    CCVector3 P(static_cast<PointCoordinateType>(x),
                                   static_cast<PointCoordinateType>(y),
                                   static_cast<PointCoordinateType>(z));
		pc->addPoint(P);
		}
	}

	QVariant xVar = QVariant::fromValue<int>(rasterX);
	QVariant yVar = QVariant::fromValue<int>(rasterY);
	pc->setMetaData("raster_width",xVar);
	pc->setMetaData("raster_height",yVar);
}
```

I am in the painful process of configuring a build at present, so then I might submit a pull req
