### ISSUE TITLE
Computing octree takes extremely long with tiny dimensions

### ISSUE THREAD

**Issue by Ghostkeeper** [cloudcompare/trunk#216]
I tried opening an STL mesh with Cloud Compare recently, but it took about half an hour to load it, even though it's just a 60kB file. I suspect that this is due to the nature of octrees, because the mesh might overlap some major octree border and its dimensions are very small (distance within 3 units of each other). It might be possible to fix by confining the octree's space to within the bounding box of the scene. Another possible source might be floating point rounding errors.

**Expected behaviour**: The 60kB STL file loads at least faster than the 300MB point clouds that Cloud Compare has no trouble with.
**Observed behaviour**: It takes extremely long to load the mesh. One processor core is maxed out for half an hour. The loading bar slowly progresses. The program does not take an abnormal amount of memory, but one processor core is maxed out. It's hard to cancel due to the infrequent window drawing updates, but once you cancel the program runs fast again but no octree could be computed.
**System and version**: Windows 7, 64-bit, Cloud Compare version 2.6.1, 64-bit.
**Steps to reproduce**: Download this model to try: [Download](http://dulek.net/Cylinder.stl). Open it with Cloud Compare. Watch how slow it gets during the computing of the Octree.

**Comment by cloudcompare** [comment]
Indeed, this is a known bug (due to the fact we increased the max octree depth in the last version and the vertex merging algorithm was using the max depth by default...).

You can download the beta version here:
http://www.cloudcompare.org/release/CloudCompare_v2.6.2.beta_bin_x64.zip

Thanks for the feedback anyway!
