### ISSUE TITLE
cloudcompare crashes when starting from server provided write protected application folder on OSX

### ISSUE THREAD

**Issue by danieltrentman** [cloudcompare/trunk#219]
Running 2.6.1 cloudcompare  on OSX 10.9.  Runs from my folder.  Move the application to a server provided write protected folder (for access by class machines) and CC crashes as does ccViewer.

**Comment by asmaloney** [comment]
Offhand I don't know what would be writing in the app itself.  Does the crash log give any useful info?

**Comment by danieltrentman** [comment]
Looks like you are correct, not directly an unpermitted file write failure.  Perhaps a dynamic lib link problem but only when the app is on a file server share, not on the local desktop.

from system.log :
-------------
Jun 28 15:41:14 trentman-dt-01.admin.cmes.utah.edu ReportCrash[26733]: Failed to create CSSymbolicatorRef for CloudCompare[26732]
Jun 28 15:41:14 trentman-dt-01.admin.cmes.utah.edu ReportCrash[26733]: Failed to create dSYM-less CSSymbolicatorRef for CloudCompare[26732]
Jun 28 15:41:15 trentman-dt-01 com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000015.CloudCompare[26732]): Service exited due to signal: Abort trap: 6
Jun 28 15:41:15 trentman-dt-01.admin.cmes.utah.edu ReportCrash[26733]: Saved crash report for CloudCompare[26732] version ??? to /Users/trentman/Library/Logs/DiagnosticReports/CloudCompare_2015-06-28-154115_Mac-4.crash
-------------

DIagnosticReport:
--------------
Process:               CloudCompare [26732]
Path:                  /uufs/*/CloudCompare.app/Contents/MacOS/CloudCompare
Identifier:            CloudCompare
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           CloudCompare [26732]
User ID:               7016
Date/Time:             2015-06-28 15:41:14.045 -0600
OS Version:            Mac OS X 10.10.3 (14D136)
Report Version:        11
Anonymous UUID:        3D7D29DB-556E-5898-63FF-A2EFD04940F0
Time Awake Since Boot: 190000 seconds
Crashed Thread:        Unknown
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Backtrace not available
Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000006  rcx: 0x00007fff5fbff678  rdx: 0x0000000000000000
  rdi: 0x000000000000130f  rsi: 0x0000000000000006  rbp: 0x00007fff5fbff6a0  rsp: 0x00007fff5fbff678
   r8: 0x00007fff5fbff5e0   r9: 0x00007fff70a60300  r10: 0x0000000008000000  r11: 0x0000000000000206
  r12: 0x0000000003402b88  r13: 0x0000000003900400  r14: 0x00007fff70a60300  r15: 0x00007fff5fbffb90
  rip: 0x00007fff88865286  rfl: 0x0000000000000206  cr2: 0x00007fff70f9cfd8
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133
Binary images description not available
External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 1
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 81171
    thread_create: 0
    thread_set_state: 0
---------------

**Comment by asmaloney** [comment]
@danieltrentman Could you please try this with the 2.7 release and close this issue if it's working for you?

**Comment by danieltrentman** [comment]
works: 2.7 on OSX 10.10 with cloudcompare on an NFS server mount
thanks for the fix
