### ISSUE TITLE
cloudcompare crashes in "Extract cloud sections along polylines"

### ISSUE THREAD

**Issue by HPryde** [cloudcompare/trunk#222]
CC v2.6.1 (Windows 7 & 8)

- Select two LAS files
- Select "Extract cloud sections along polylines"
- Define alignment
- Generate orthogonal sections along a path
- Extract points along active sections
- Starts to extract sections then crashes

Cheers

**Comment by cloudcompare** [comment]
Thanks for the feedback.

Can you try to reproduce the crash with the beta version?
http://www.cloudcompare.org/release/CloudCompare_v2.6.2.beta_bin_x64.zip

**Comment by HPryde** [comment]
Hi,

Yes it still crashes.

Regards,

Hamish

**Comment by HPryde** [comment]
Screen grab attached

**Comment by dgirardeau** [comment]
I can't reproduce it on my side (and I can't see your image - I guess you have to paste it via the github interface).

Can you share your data with me? Is it easily reproducible?

**Comment by HPryde** [comment]
![capture](https://cloud.githubusercontent.com/assets/13343835/8693438/a9f1ffc6-2b09-11e5-9888-8784b7a42176.JPG)

**Comment by dgirardeau** [comment]
Oh, and does it crash also with a single cloud?

**Comment by HPryde** [comment]
No. Single cloud works ok. I will dropbox files tomorrow.

**Comment by dgirardeau** [comment]
Good. I'll look in this direction meanwhile.

**Comment by HPryde** [comment]
https://www.dropbox.com/sh/blumyngqfkagbva/AADZUya1QJEMPNivBD3-A-oWa?dl=0

**Comment by cloudcompare** [comment]
Thanks for the data.

Sadly I can't reproduce the bug ;). Did you use specific parameters? Do you extract the lower or the upper contour?

**Comment by cloudcompare** [comment]
Ah! I finally reproduced it. It's when you generate the section clouds (not the profiles). I'll investigate asap.

**Comment by cloudcompare** [comment]
Okay the issue is fixed. Thanks again for the feedback.

You'll find the latest beta version here: http://www.cloudcompare.org/release/CloudCompare_v2.6.2.beta_bin_x64.zip
