### ISSUE TITLE
qPCL plugin does not compile

### ISSUE THREAD

**Issue by juehess** [cloudcompare/trunk#228]
After commit #0957b6d the qPCL plugin does not compile anymore.
I think the reason is the renaming of the color type from colorType to ColorCompType.

**Comment by cloudcompare** [comment]
Indeed ;). I generally skip the compilation of qPCL (as it sooooooooo long). Sorry about that. That's fixed now.

**Comment by fangxu622** [comment]
when compiled the cloudcompare completely, the Plugin doesn't work ,as show in figured,why? who can solve it
![1](https://cloud.githubusercontent.com/assets/16681534/12289379/2bad9746-ba16-11e5-9a10-d78297a38862.png)

**Comment by cloudcompare** [comment]
What is displayed in the Console (at the beginning). Does CC try to load any of the plugins DLLs?

Are the plugins DLLs in the 'plugins' folder next to CloudCompare.exe? (have you 'installed' the project once compiled - i.e. have you generated the 'INSTALL' project?)
