### ISSUE TITLE
Transform Command Line Hangs With Meshes in 2.6.2B

### ISSUE THREAD

**Issue by m-cross** [cloudcompare/trunk#229]
When running 2.6.2 beta from command line using the following:

-O "D:\66000_84000_A_Filtered.las" -AUTO_SAVE OFF -DELAUNAY -AUTO_SAVE OFF -M_EXPORT_FMT FBX -FBX_EXPORT_FMT FBX_binary -APPLY_TRANS "D:\CC_Transform.txt"

CloudCompare hangs after saving following the delaunay command. The transform text file contains an identity matrix as follows:

1.0 0.0 0.0 0.0
0.0 1.0 0.0 0.0
0.0 0.0 1.0 0.0
0.0 0.0 0.0 1.0

Transform works fine with point clouds, only hangs when applied to triangulated meshes.

**Comment by cloudcompare** [comment]
Wow, two bugs in the same call ;)

1. The 'auto save' option was ignored by the Delaunay command (normally you just need to set it once at the beginning of the command line)

2. When (wrongly) saving the mesh, CC was creating a looping hierarchy (the mesh was the parent of the cloud which was itself a parent of the mesh ;) causing an infinite loop when transforming the mesh!

Thanks for the feedback. The two bugs are now fixed (as a reward... you can download the new beta version ;).
