### ISSUE TITLE
-GLOBAL_SHIFT Command Line Unknown in v2.6.2B

### ISSUE THREAD

**Issue by m-cross** [cloudcompare/trunk#230]
In the latest 2.6.2 Beta binary download the command line:

call "C:\CloudCompare_v2.6.2.beta_bin_x64\CloudCompare.exe" -O "D:\66000_84000_A_Filtered.las" -GLOBAL_SHIFT AUTO -C_EXPORT_FMT LAS -SAVE_CLOUDS

Will fail with 'Unknown or misplaced command: -GLOBAL_SHIFT'
Command also fails if global_shift is moved before open command.

**Comment by cloudcompare** [comment]
The GLOBAL_SHIFT option must be put directly after "-O" (it's a sub-option of "O")

**Comment by kannes** [comment]
For anyone else ending up here, an working example:

`-O -GLOBAL_SHIFT AUTO filename.ext`
