### ISSUE TITLE
Mesh precision lost when coordinates are too large

### ISSUE THREAD

**Issue by mikecutters** [cloudcompare/trunk#232]
First of all, I love your work, each time I use cloudcompare I am amazed.

I have been comparing a scanned surface to a triangulated mesh, and the local coordinate system is in the order of 400000,800000,0.

When importing both the point cloud and the mesh I am prompted to do a global shift, which shifts both files.  The precision of the point cloud is retained, but the mesh precision is lost, despite translation.  This is easy to workaround as I can just translate the mesh prior to importing, but initially I was unaware of the loss of precision.

Many thanks
Mike

**Comment by cloudcompare** [comment]
Hi,

What is the file format of the mesh?

**Comment by mikecutters** [comment]
FBX. I also tried an stl with similar results.

Thanks



-------- Original message --------

**Comment by cloudcompare** [comment]
Well, if you use binary STL files it's not a surprise the coordinates are internally represented on 32 bits only. Therefore you can't keep a good precision when saving big coordinates. And what I mean here is that the precision will be lost as soon as you save the mesh in STL format (not when you load it in CloudCompare). ASCII STL files can be more accurate.

For FBX, the issue can be the same (as the internal representation of coordinates is also 32 bits) but you could set a global transformation matrix so as to reduce this effect (just as the 'Global Shift' mechanism of CC). Of course It depends on how you have generated the FBX file.

**Comment by mikecutters** [comment]
Thank you for your response!  That explains it.

**Comment by cloudcompare** [comment]
Good ;)
