### ISSUE TITLE
unable to open .las files that are saved by lastools

### ISSUE THREAD

**Issue by squeakus** [cloudcompare/trunk#233]
Hi,
I am getting a strange error and it might be because of something I changed. I am able to open las files but and that I have changed or saved using lastools don't seem to open. Instead I get the following error message:

An error occurred while loading 'pt000281': process canceled by user
An error occurred while loading 'pt000281_ground': the third-party library in charge of saving/loading the file has failed to perform the operation

This maybe because I something I did during compilation. I was getting a weird error message when compiling with the liblas options turned on, I hit an error on line 1179 of libs/qCC_IO LASFilter.cpp, it expected "(" before the "or" token. In order to get it to compile I simply commented out that catch:
  // catch (const std::out_of_range& or)
  //   {
  //     ccLog::Error(QString("Liblas exception: '%1'").arg(or.what()));
  //     result = CC_FERR_THIRD_PARTY_LIB_EXCEPTION;
  //   }

could that have caused the above error or is something else going wrong?

**Comment by cloudcompare** [comment]
Well if you have commented out this section and still get an error message, then it means that liblas did send an exception anyway. But which one...

Instead of commenting out the section, can you include 'exeption' at the beginning of the file:
```
#include <exception>
```
Hopefully it should fix the compilation issue.
Afterwards if you get a new error message (starting by 'Liblas exception: XXX') it will be more informative. And it will probably be an issue with the LAS version number (1.4 is not supported by liblas for instance).

**Comment by squeakus** [comment]
I uncommented the code and added #include <exception> but I am getting the
same compilation issue:

In member function ‘virtual CC_FILE_ERROR LASFilter::loadFile(QString,
ccHObject&, FileIOFilter::LoadParameters&)’:
/home/jonathan/Applications/cloudcompare/libs/qCC_io/LASFilter.cpp:1180:36:
error: expected ‘)’ before ‘or’ token
    catch (const std::out_of_range& or)

I also tried the windows binary for cloudcompare and it managed to open the
lastool files so I think it might be something else.

**Comment by cloudcompare** [comment]
That's strange indeed.

Which OS/compiler are you working with?

**Comment by squeakus** [comment]
I am compiling it on ubuntu 14.04 and my gcc version is:
gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2

**Comment by cloudcompare** [comment]
Then maybe:
```
#include <stdexcept>
```
(http://en.cppreference.com/w/cpp/error/out_of_range)

**Comment by squeakus** [comment]
I tried stdexcept but I get exactly the same error. I have never seen an
error like this before but it seems to be unhappy about how the argument is
being passed into the catch.

**Comment by cloudcompare** [comment]
Indeed It's a new habit of mine to use const ref for exceptions but it might not be a good idea with gcc.

Have you tried simply:
```
 catch (std::out_of_range or)
```

**Comment by squeakus** [comment]
I tried taking off the const but I got the same error:
 error: expected ‘)’ before ‘or’ token
    catch (std::out_of_range& or)

I also tried removing the & but it didn't make a difference.

**Comment by cloudcompare** [comment]
Ah! Then we're doomed...  We will need the help of a Linux guru ;)

Anyway it's weird that you get an exception if you say that the file works with the Windows version...

**Comment by squeakus** [comment]
No problem, I know one or two around the office. thanks again for all your
help!

**Comment by squeakus** [comment]
I got it! "or" is a keyword, i don't know why I didnt spot it sooner. When
I changed or to oor then it worked, strange that your compiler didnt pick
it up.

**Comment by cloudcompare** [comment]
'or' ?! Well I know the '||' and '|' operators but not the explicit 'or'. Where is it defined?

**Comment by cloudcompare** [comment]
Oh here it is:
> The or operator is the text equivalent of ||. There are two ways to access the or operator in your programs: include the header file iso646.h, or compile with the /Za (Disable language extensions) compiler option.
https://msdn.microsoft.com/en-us/library/f355wky8.aspx

**Comment by cloudcompare** [comment]
The sources have been fixed. Thanks for the feedback.
