### ISSUE TITLE
Horn registration failure

### ISSUE THREAD

**Issue by dgirardeau** [cloudcompare/trunk#236]
This two sets of 4 points make the Horn registration step fail (Horn registration is used in the point pair based alignment tool):

0 0 0
10.1918 32.7471 0
98.4476 0 0
22.2453 -40.236 0.0519957

And

0 0 0
34.220131234538 0 0
29.143768215774 93.921515518778 0
-31.892554477142 33.146439000266 0.357561727645

It works with any subset of 3 points but it fails with the 4 points at once!

**Comment by cloudcompare** [comment]
Ok that's fixed (we were only computing positive eigenvalues...)
