### ISSUE TITLE
ssl missing

### ISSUE THREAD

**Issue by ghislainp** [cloudcompare/trunk#238]
Under debian jessie, libqp.so has a missing dependency on libssl. Make fails at the linking step. I manage to add SSL in CMakeList.txt and it works, but being not an expert of CMakeList.txt at all, you'll find a better solution than mine.

**Comment by cloudcompare** [comment]
What's libqp?! Have you identified which component relies on it?

**Comment by ghislainp** [comment]
Sorry, I meant libpq (postgresql).
Ghislain

Linking CXX executable CloudCompare
../CC/libCC_CORE_LIB.a(PointProjectionTools.cpp.o): In function 
`FindNearestCandidate(unsigned int&, 
std::_List_iterator<CCLib::PointProjectionTools::IndexedCCVector2*> 
const&, 
std::_List_iterator<CCLib::PointProjectionTools::IndexedCCVector2*> 
const&, std::vector<CCLib::PointProjectionTools::IndexedCCVector2, 
std::allocator<CCLib::PointProjectionTools::IndexedCCVector2> > const&, 
std::vector<HullPointFlags, std::allocator<HullPointFlags> > const&, 
float, float, bool)':
PointProjectionTools.cpp:(.text+0x1a1c): multiple definition of 
`FindNearestCandidate(unsigned int&, 
std::_List_iterator<CCLib::PointProjectionTools::IndexedCCVector2*> 
const&, 
std::_List_iterator<CCLib::PointProjectionTools::IndexedCCVector2*> 
const&, std::vector<CCLib::PointProjectionTools::IndexedCCVector2, 
std::allocator<CCLib::PointProjectionTools::IndexedCCVector2> > const&, 
std::vector<HullPointFlags, std::allocator<HullPointFlags> > const&, 
float, float, bool)'
CMakeFiles/CloudCompare.dir/ccContourExtractor.cpp.o:ccContourExtractor.cpp:(.text+0x0): 
first defined here
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to 
`SSL_get_peer_certificate@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to 
`CRYPTO_num_locks@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libgdal.so: undefined 
reference to `lzma_stream_decoder@XZ_5.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to 
`SSL_CTX_use_certificate_chain_file@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to 
`SSL_use_certificate_file@OPENSSL_1.0.0'

etc

**Comment by cloudcompare** [comment]
How strange... There shouldn't be any dependency with postgresql...

Apparently it's coming from GDAL. Can you try to compile without GDAL support?

Or at least can you post the lines you added to your CMake file?

**Comment by ghislainp** [comment]
Bonjour,

Désolé du bruit, c'etait surement une mauvaise interacion avec anaconda. 
Sur une install fraiche, ca marche sans probleme.
Cordialement,
Ghislain
