### ISSUE TITLE
Make rotation center selection more user friendly

### ISSUE THREAD

**Issue by KAMI911** [cloudcompare/trunk#240]
I tried on several computers but the rotation center selection is not so user friendly. When I click on cross-hair icon the I click to rotation center the program become unresponsive. And the selection takes loooong seconds. It would be nice to make this faster or even better to assign rotation center to mouse + key combo immediately (or use the middle button).

Thanks!

**Comment by cloudcompare** [comment]
What version are you using?

**Comment by KAMI911** [comment]
On Linux 2.6.0 from PPA
On Windows 2.6.2 beta

**Comment by cloudcompare** [comment]
And you get the same 'slow' behavior on Windows? Can you check that the 'Use OpenGL for picking' option is disabled in the Display Parameters on the 2.6.2 version?

We had issues with slow OpenGL GPUs/drivers before, this is why we do it with the CPU now.

**Comment by KAMI911** [comment]
I will check it tomorrow on Windows. For Linux, is there any newer version in PPA?

**Comment by cloudcompare** [comment]
I believe the 2.6.1 is available on Romain Janvier's PPA. It should support the CPU point picking if I'm not mistaken.

**Comment by ORNis** [comment]
2.7.0beta is coming and maybe a kind of "daily build" channel too. But I think I won't support 12.04 and maybe 14.04 anymore.

**Comment by KAMI911** [comment]
It would be nice if you support at least the latest LTS edition. Fresher builds that I can testing related to this bug?

**Comment by ORNis** [comment]
yes, it's not really sure for 14.04 but I made my choice for 12.04. I spend most of my packaging time handling corner case for specific versions of ubuntu... and my packaging time is 90% my free time (I'm in vacation today for exemple). In the meantime 16.04 is comming

**Comment by ORNis** [comment]
2.6.3 packages are available for 14.04 and 15.10 in bintray https://bintray.com/ornis/CloudCompare/CloudCompare/view/readmore#read. 2.7 should follow quickly, but only for 16.04. If it's fine for you, I close this issue.

**Comment by ORNis** [comment]
Closed as fixed since 2.6.1.
