### ISSUE TITLE
Incorrect calculation of dip direction

### ISSUE THREAD

**Issue by ao2** [cloudcompare/trunk#241]
Hi,

after using the qFacets plugin the geologists at [Stage s.r.l.](http://www.stagesrl.com/) found a bug about how the dip direction is calculated in CloudCompare.

This problem has also been mentioned in https://github.com/cloudcompare/trunk/issues/183 and confirmed by @luca-penasa.

The concept of "dip direction" can be visualized like that:

> The dip direction is the direction (measured as a clockwise angle relative to the North) in which a liquid flows when poured on a plane from the top.

From this definition it is clear that parallel planes must have the same dip direction, when planes are represented with facets we can say that parallel facets must have the same dip direction regardless of whether their normal points upwards or downwards.

See the image below of a particular case of coplanar facets with opposed normals, they must have the same dip direction.
![01_dipdir_calculation_minimal_example_top_view](https://cloud.githubusercontent.com/assets/1249395/10968757/c065146a-83c3-11e5-937b-10535185a49e.jpg)

But with the current code they have not.

Another test to see the incorrect behavior of the current calculation can be this one:

  1. Create a sphere: File > Primitive factory > Sphere (Create)
  2. Select "vertices" and Extract facets (kd-tree) using the qFacets plugin (default settings are OK).
  3. Toggle visibility off for the Sphere.
  4. Select "vertices [facets]" and Show the Stereogram (default settings are OK) and use the Interactive filter to see that non-parallel planes have the same dip direction, which is not right.

The problem can be solved by considering all the normals pointing upwards when calculating the dip direction, and this can be done quite easily using the sign of N.z, like that:

```diff
diff --git a/libs/qCC_db/ccNormalVectors.cpp b/libs/qCC_db/ccNormalVectors.cpp
index ae6d5c3..0582a79 100644
--- a/libs/qCC_db/ccNormalVectors.cpp
+++ b/libs/qCC_db/ccNormalVectors.cpp
@@ -855,8 +855,16 @@ void ccNormalVectors::ConvertNormalToDipAndDipDir(const CCVector3& N, PointCoord
                return;
        }

+       // The Dip direction must be the same for parallel planes, regardless
+       // of whether their normals point upwards or downwards.
+       //
+       // The calculations below give the correct value for planes with the
+       // normal pointing upwards, so use the sign of N.z to invert the
+       // normals if they point downwards.
+       double Nsign = copysign(1.0, N.z);
+
        //"Dip direction is measured in 360 degrees, generally clockwise from North"
-       double dipDir_rad = atan2(N.x,N.y); //result in [-pi,+pi]
+       double dipDir_rad = atan2(Nsign * N.x, Nsign * N.y); //result in [-pi,+pi]
        if (dipDir_rad < 0)
                dipDir_rad += 2.0*M_PI;
```

After this change parallel facets have the same dip direction.

I used the sign to avoid introducing temporary variables for the inverted normals, If this is OK to you I will send a pull request, along with a commit which simplifies also the calculation of the dip angle.

Thanks,
   Antonio

**Comment by cloudcompare** [comment]
Ok. Can you make a pull request then? And update the 'history.txt' file by the way (in the 'bug fixes' section of the latest version)
