### ISSUE TITLE
Random subsample is not random for big cloud

### ISSUE THREAD

**Issue by PeterJCC** [cloudcompare/trunk#245]
Hi

Random sub-sample is not working correctly with big clouds = 150 Mega Points.

Only first aprox. 15 Mpoints are sub-sampled correctly but then probability of point will be removed is higher as should be.

My test:
-generate cloud with 150 M points, points [0, 0, 0], [1, 0, 0] ... [149 000 000, 0, 0]
-then sub-sample randomly to 10 M points
-generate histogram of X values (1000 bins in my case)

You could see that at the end of cloud there is much less points as should be. Cloud is less dense at the and of cloud.

![cc random subsample](https://cloud.githubusercontent.com/assets/15786001/11067668/a90b2092-87c5-11e5-8a6f-c9241a6702e4.png)

X axis = bins of X values of sub-sampled cloud
Y axis = counts of points in bin

**Comment by cloudcompare** [comment]
That's very interesting! We'll have to investigate, but this phenomena may come from the way the algorithm works.

First let's me point out that the algorithm only guarantees a 'minimum distance between points'. In effect it randomly picks a point, and then it removes all the neighbors that are closer to the specified min distance. The process is repeated as long as all the points have been either randomly picked or removed.

However I'm not sure this explains what you have found.

**Comment by cloudcompare** [comment]
Forget my previous message, I thought you were using the SPATIAL subsampling algorithm.

The RANDOM algorithm is much simpler. We simply pick the given number of points randomly! The selected point indexes are generated with the C++ rand() function. Of course if the same point is selected multiple times, we ignore it and generate a new index...

The phenomena you described may come from the way the rand() function works. But once again I'm not really sure and we should conduct more tests ;)
