### ISSUE TITLE
OBJ cloud export missing in 2.6.2?

### ISSUE THREAD

**Issue by eliot-lightcraft** [cloudcompare/trunk#253]
I loaded in a LIDAR point cloud, and am attempting to export it in .OBJ format. However, File->Save does not list this as available. I have selected the cloud, as seen in the screencap.

The point cloud I am using is at https://www.dropbox.com/s/hlavw11ekv9be51/market_reduced%20-%20Cloudsubsetbinary.ply?dl=0.

I attached a screencap to this to show the cloud is selected. 

![cloudcomparenoobj](https://cloud.githubusercontent.com/assets/2244258/11203044/32b91f32-8ca4-11e5-88bc-a10aef49f371.png)

The available export settings are:
CloudCompare
ASCII
LAS
E57
PLY
VTK
SHP
.pn
.pv
.pov
.pcd

(I'm writing this out to ensure that people don't simply respond 'Click File-Save As . . there *is* no File-Save As.)

Did the OBJ handler get removed from 2.6.2, or is there something simple that I'm missing? The docs mention OBJ import/export, but it doesn't show up on the file saving formats.

Thanks!

**Comment by cloudcompare** [comment]
It's simply that we consider the OBJ format as a mesh-only format.

Technically it should be possible to save clouds in an OBJ file (i.e. a file with vertices only, and no polygon data). But I don't know any other software that would be able to load it. Do you know any? Should we enable this?

**Comment by eliot-lightcraft** [comment]
The software I'm trying to get point clouds into is the Instant Mesh
example Win64 binary at http://igl.ethz.ch/projects/instant-meshes/. It
accepts either .ply or OBJ, but the .ply files I tried exporting from
CloudCompare aren't being read into Instant Mesh when I tried this.

The Instant Mesh site has a set of example .ply files, which are very
similar to the ones that CloudCompare exports, but something is subtly
different, and I get an error from Instant Mesh.

The Instant Mesh binaries and source code are downloadable; you may want to
take a look at this as they have solved a really big problem in generating
automatic but well-ordered meshes, which your user base could probably
absolutely love after fighting weird triangulation methods for hours.

Thanks!

-Eliot

**Comment by cloudcompare** [comment]
Instant Mesh is a very nice tool. But did you understand that the software works on meshes only? It's used to *remesh a surface*. It doesn't work on point clouds.

This is why it expects OBJ and PLY files. Even though PLY files can store both clouds and meshes, I guess they only load PLY files with meshes. I just tested with a **mesh** PLY file generated by CC and it works fine.

Anyway to use Instant Mesh you'll have to first generate a mesh from your point cloud (with CC or Meshlab). For an aerial LIDAR cloud it may be sufficient to use the 2.5D Delaunay triangulation. Then you'll be able to save this mesh as an OBJ or PLY file.

**Comment by eliot-lightcraft** [comment]
Check out the description video at 2:46 -- they can use raw point clouds as
an input. This capability is also mentioned in the software description
page, hence my interest in it.

-Eliot

**Comment by cloudcompare** [comment]
Looking at the code it appears that it's more a kind of hidden feature! By default the *load_ply* method is called with a *load_face* boolean which is forced to true. In effect the program will look for vertex indexes (i.e. polygonal data) and therefore it will reject PLY clouds.

There's a 'load_pointcloud' method that is only called if an 'ALN' file is selected. An ALN file is an "alignment file". It can be associated to multiple (cloud) PLY files and it contains orientation matrices for each cloud. An ALN file can be generated with Meshlab (load a cloud and then use 'File > Save project' and eventually select the ALN format). Sadly there's a glitch in their code and even if you load an ALN file, they don't change the *load_face* boolean and the program will still reject the PLY clouds.

I patched the code and was able to load a PLY cloud (with a dummy ALN file). A lot of processing occurred... and eventually nothing was displayed :(. I can click on the *Solve* buttons but no mesh is generated. I guess this feature is a bit deprecated.

Another concern of mine is that contrarily to what the authors imply in their video, it appears that the algorithm requires normals (*just like the Poisson Reconstruction algorithm*). And my pinky tells me that if you don't get clean normals, you won't get a very nice result ;).

By the way, the *load_ply* and *load_obj* methods don't handle normals. This is why they can't be used to import a cloud and the only solution is to use an ALN file... I guess the authors must use ALN files to compose and orient multiple 2.5D scans. This allows them to compute clean and robust normals.

From this point you'll have to ask the authors directly. I'll be very interested to see how their algorithm works with a real point cloud as input (i.e. without multiple scans and their associated sensor position, with noise, etc.).

P.S.: sorry to be a bit suspicious but I saw so many "magical" cloud meshing algorithms in my life that I become more skeptical each time...

**Comment by cloudcompare** [comment]
After a little more digging: it's worst than I thought. There's no glitch in their code, they actually only load PLY meshes! Even with an ALN file. It's because they use the mesh structure to compute the normals!

Of course this way they obtain very clean normals. But if you start from a mesh, use it to compute perfect normals, and eventually you mesh the vertices again with perfect normals, I don't see the point. Poisson Reconstruction also works very well with this silly workflow...

Maybe what they meant is that they can 'remesh' a mesh using only its vertices (and normals)?

**Comment by eliot-lightcraft** [comment]
Weird. Thanks so much for looking into this! I need to send this to their
developers. Is the .OBJ import any better?

**Comment by cloudcompare** [comment]
The OBJ importer doesn't handle normals either. Therefore you can only load a mesh with it (and it's good because OBJ files are never used as cloud storage files).

**Comment by eliot-lightcraft** [comment]
OK. I emailed the author Wenzel Jakob this (wenzel@inf.ethz.ch) and cc:d
you on it, so hopefully we can track down an explanation.

Thanks for looking at this!

-Eliot
