### ISSUE TITLE
segfault at point list picking

### ISSUE THREAD

**Issue by luca-penasa** [cloudcompare/trunk#254]
the point picking tool crashes when one presses the "ok" button (the one with the green check mark)

the assert is in ccDBRoot.cpp:260

```cpp
	if (objects.empty())
	{
		assert(false);
		return;
	}
```

is it a debugging assert that remained there for mistake?

Luca

**Comment by dgirardeau** [comment]
More or less. It was to prevent an unnecessary call (I fixed this on the other side).

Thanks for the feedback.

**Comment by luca-penasa** [comment]
Same segfault when:
- open and select cloud
- open point list picking tool and pick some points 
- press V mark
- reselect same cloud
- open pick point list
- press X mark

Can you confirm?

Thus something its still calling that method without objects in the container...

**Comment by dgirardeau** [comment]
Indeed :D

That's fixed now.

**Comment by luca-penasa** [comment]
:+1:  great!
