### ISSUE TITLE
RAND_MAX+1 warning on Linux

### ISSUE THREAD

**Issue by adrian17** [cloudcompare/trunk#262]
I got this warning while trying to compile on Linux. The value of RAND_MAX on my system is 2147483647.

![screenshot from 2015-12-21 20-24-25](https://cloud.githubusercontent.com/assets/4729533/11939240/04c7c1da-a821-11e5-9533-4dae5d2c0a80.png)

**Comment by dgirardeau** [comment]
Indeed! I just fixed this (I replaced the old rand() call to the new std::random mechanism.

Thanks for the feedback.
