### ISSUE TITLE
Regression with contour extraction

### ISSUE THREAD

**Issue by adrian17** [cloudcompare/trunk#263]
Introduced in 6d62666c9d9ed0555f688cf5bf9497caa4f53d89.

To reproduce: open extraction tool, make a simple (just 2 points) polyline, choose "extract points along active sections", keep default settings.
Before: the contour fits the shape quite good: After: not at all.

![screenshot from 2015-12-22 15-14-07](https://cloud.githubusercontent.com/assets/4729533/11957085/7d1a0488-a8bf-11e5-802f-a76c89fec130.png)
![screenshot from 2015-12-22 15-04-42](https://cloud.githubusercontent.com/assets/4729533/11957087/7d28cbda-a8bf-11e5-8fd3-be20c127605e.png)

**Comment by dgirardeau** [comment]
Are you sure this is this exact commit? Or 47691dd5eab5a63ecb3553a06cbe71456e4d3aca?

**Comment by adrian17** [comment]
I've located it with git bisect and just tested it again, I'm certain:
6d62666 and forward - it's bugged (lower screenshot on the post above). 
2037c85 (commit just before it) - it's working correctly.

I've been testing it on Linux; I've just checked the 2.6.3.beta download on Windows, it's also affected.

**Comment by dgirardeau** [comment]
Well I just wanted to check because in this case it might not be exactly a bug but more a voluntary modification of the behavior of the algorithm ;).

What if you set a much lower 'max edge length' parameter?

**Comment by adrian17** [comment]
Lowering it over an order of magnitude doesn't seem to change the contour at all.

Here's a video with a reproduction, with 2.6.2 and 2.6.3beta. https://puu.sh/m58qv/b8da6c349c.mp4

**Comment by dgirardeau** [comment]
Ok, now I remember what I did at that time ;). And I fixed the bug.

Once again thanks for the feedback!
