### ISSUE TITLE
ignore borders - Rasterize - MAC OS X V 2.6.1 (64 Bits) - RESOLVED

### ISSUE THREAD

**Issue by geoxluca** [cloudcompare/trunk#264]
Hi everyone
wen I generate the contour lines, "ignore borders" don't work. In fact, the contour lines on the borders remain.
Thank you

**Comment by asmaloney** [comment]
Thanks @geoxluca.

What version of Mac OS X are you using?
Can you add images that show the issue?
Do you have access to the Windows version?
If so, does it have the same problem?

(I'm not a heavy user of CC - I haven't used that feature.  Maybe @dgirardeau has some input too.)

**Comment by geoxluca** [comment]
Mac Version > 10.11.1
I have not a windows version
This is a screen shot 
![contour_lines](https://cloud.githubusercontent.com/assets/10447191/12023374/1e634664-ad99-11e5-8a79-fdad228ede99.jpg)

**Comment by dgirardeau** [comment]
Not sure but it might be maybe because the 'borders' are not the borders of the grid (as the tile is oblique relatively to the bounding-box).

Otherwise it may be due to the parameters. Have you left the empty cells empty or did you use another parameter?

**Comment by geoxluca** [comment]
Than'k for answer Daniel.
Yes the Empty cells command is set on empty.
Really, I think that the problem is the border grid, in fact in the attached image I have cramped area in Rasterize > Edit Grid command and, in those zones the contour lines are corrected.
But, How can I rotate and cut the bounding-box on all my surface without change the coordinate system?
![contour_ok](https://cloud.githubusercontent.com/assets/10447191/12032588/1892f53c-ae1a-11e5-9f72-05a2161b4501.jpg)

**Comment by cloudcompare** [comment]
You could transform your cloud to make it straight. Then apply the Rasterize tool and eventually apply the inverse transformation to the ff contour lines (with 'Edit > Apply transformation' - you can copy the transformation from the Console or the 'Transformation history' field of the cloud properties and there's an "inverse" checkbox in the tool).

**Comment by asmaloney** [comment]
@geoxluca Did Daniel's suggestion work for you?  Please close this if it is no longer an issue for you.

**Comment by geoxluca** [comment]
yes, it could be a solution
