### ISSUE TITLE
ZOOM in Render to file - Mac Osx V 2.6.1 (64 Bits) - RESOLVED

### ISSUE THREAD

**Issue by geoxluca** [cloudcompare/trunk#265]
Zoom in "Render to file" command don't work. In fact, when I set zoom = 5, the result image is 5x large but it is almost all blu and object is very small in the down left border

**Comment by asmaloney** [comment]
(Again, please include version of OS and images showing the issue if possible.)

**Comment by geoxluca** [comment]
Ok asmaloney, sorry
Mac OSX 10.11.1
this is a screen shot
![manduria](https://cloud.githubusercontent.com/assets/10447191/12023514/873a8f52-ad9a-11e5-8980-40ccec366583.jpeg)

**Comment by dgirardeau** [comment]
Does it work with a X4 zoom? In this case it might be simply that you have reached the graphic card memory limit...

**Comment by geoxluca** [comment]
Hi Daniel, thank you for answer
unfortunately, there is the same problem with other zoom set 2X, 4X etc.
Same problem in MacBook with different hardware configuration too.

**Comment by geoxluca** [comment]
just now I tried in windows and ZOOM not is a problem

**Comment by cloudcompare** [comment]
Ok. I guess you'll have to wait for the 2.7 Mac OS version then (it won't come out very soon however).

**Comment by geoxluca** [comment]
oh my God :(

**Comment by asmaloney** [comment]
@dgirardeau Is this something that's been fixed since 2.6.1?

**Comment by cloudcompare** [comment]
Nope but it's probably linked to an OpenGL issue (which should hopefully be fixed by using Qt 5 + QOpenGLWidget)

**Comment by asmaloney** [comment]
Just wanted to confirm that this should be fixed for the upcoming 2.7 release.

**Comment by geoxluca** [comment]
Yes Asmaloney, you are working in windows? I saw that in windows OS this problem was resolved

**Comment by cloudcompare** [comment]
:)

Andy (Maloney) is the one who maintains the Mac OS version. We just worked hard together to pull out the 2.7 release. It should make everything works on Windows / Linux / Mac OS the same.

**Comment by geoxluca** [comment]
I hope, soon. Tks

**Comment by asmaloney** [comment]
@geoxluca Can you please test this with the 2.7 release and close the issue if it's working for you?

**Comment by geoxluca** [comment]
@asmaloney, good words for me :)
YES NOW WORKING
thank you so much
