### ISSUE TITLE
Only 75% of the cloud is shown

### ISSUE THREAD

**Issue by yrzhanov** [cloudcompare/trunk#266]
I use Windows 7, 64 bit, CloudCompare 2.6.2
Sometimes a point cloud in .pcd format appears incomplete. Console reflects this: VBO(s) (re)initialized for cloud XXX (2.81 Mb = 75.00% of points could be loaded)
It is not a matter of memory - other (larger) clouds are loaded completely.
Is it a feature that can be changed?

**Comment by cloudcompare** [comment]
It is a memory issue, but a GPU memory one. And you have to take into account everything that's loaded on the GPU side (textures, other clouds, etc.).

In theory the points that couldn't be loaded on the GPU should still be displayed (but in a slower way). But maybe the GPU can't do anything anymore when its memory is full...

Anyway, if you want to avoid this, you can disable the 'load clouds on the GPU for faster display' option (in the Display settings).

**Comment by yrzhanov** [comment]
Changing this option did not help. Console now says only that the cloud is loaded successfully, and bounding box shows true extent of the cloud, but only ~75% of all points are displayed. (It may not be exactly 75% - I thought at first that the message is related)
![cloudcomparebug](https://cloud.githubusercontent.com/assets/4502036/12125354/e947be6c-b3b8-11e5-8a8a-d33fc3c90ef2.jpg)

**Comment by cloudcompare** [comment]
That's weird. What is the total number of points? And the graphic card model?

Can you send me the file maybe? (cloudcompare [at] danielgm.net)

**Comment by cloudcompare** [comment]
And it appears that it was indeed a bug! If the cloud size was exactly a multiple of 65536, then the last 65536 points were ignored at display time...

I've updated the online beta version (2.6.3).

Once again, thanks for the feedback!
