### ISSUE TITLE
Crash on removing a polyline

### ISSUE THREAD

**Issue by adrian17** [cloudcompare/trunk#267]
Video reproduction: https://puu.sh/mkHdr/a0f7d46daf.mp4

Happens on both the stable and beta version.

**Comment by cloudcompare** [comment]
Indeed, you shouldn't be able to delete the polyline vertices! I'll fix this asap.

**Comment by cloudcompare** [comment]
Okay, the bug is fixed. I've updated the online beta version (2.6.3).

Thanks for the feedback.
