### ISSUE TITLE
when compiled the cloudcompare completely, the Plugin doesn't work ,as show in figured,why? who can solve it

### ISSUE THREAD

**Issue by fangxu622** [cloudcompare/trunk#268]
when compiled the cloudcompare completely, the Plugin doesn't work ,as show in figured,why? who can solve it
windows 7  64, and PCL1.6 all-in-one, cmake3.0,+qt4.8(mscv2010)+VS2010
![1](https://cloud.githubusercontent.com/assets/16681534/12289587/52a92bd4-ba17-11e5-9d0a-3f6bc8a68e4e.png)

**Comment by cloudcompare** [comment]
What is displayed in the Console (at the beginning). Does CC try to load any of the plugins DLLs?

Are the plugins DLLs in the 'plugins' folder next to CloudCompare.exe? (have you 'installed' the project once compiled - i.e. have you generated the 'INSTALL' project?)

**Comment by fangxu622** [comment]
thanks for your reply, !!!  ,I'm a beginner,
I seemed to understand, I have a try, later if there is a problem to consult again, thank you very much for reply me so quickly

![3](https://cloud.githubusercontent.com/assets/16681534/12290087/9f34d842-ba1a-11e5-98b2-f4e05020c637.png)
This have something problem?

**Comment by cloudcompare** [comment]
Apparently there's no DLL file in the plugins directory.

Make sure to compile the 'INSTALL' project under Visual (you'll have first to set a valid path with access rights in CMake 'CMAKE_INSTALL_PREFIX'). And then you have to start the program from this path (and not from the default build directory).

See http://www.cloudcompare.org/doc/wiki/index.php?title=Compilation#Working_with_Visual_Studio_on_Windows

**Comment by fangxu622** [comment]
now ,I satart compiling trunk-master.
how slove it VXL,and so on,i'm Very grateful to you for what you can give me some guidance ,when compiled trunk-2.50,,it doesn't this problem...thanks

![12](https://cloud.githubusercontent.com/assets/16681534/12293690/2a82c3cc-ba30-11e5-9583-2555f311ce00.png)
![5](https://cloud.githubusercontent.com/assets/16681534/12293697/349e44f8-ba30-11e5-8ac9-60c3ba5aeb41.png)
![6](https://cloud.githubusercontent.com/assets/16681534/12293700/3bfd2318-ba30-11e5-8d2f-c6e01c7d8301.png)

**Comment by cloudcompare** [comment]
You don't need to compile all plugins.

But for the ones you need, if they have dependencies (such as VXL for qGMMReg) then you have to compile them or download binaries and then provide the path to CMake each time.

**Comment by fangxu622** [comment]
i found a new problem 
it doesn't open "las" file,
![1234](https://cloud.githubusercontent.com/assets/16681534/12318921/288d3e0e-bad9-11e5-9acd-fb9fbb63b126.png)

![321](https://cloud.githubusercontent.com/assets/16681534/12318926/2ea72f84-bad9-11e5-8b1b-98b0bd4e74b3.png)

**Comment by cloudcompare** [comment]
To open LAS files you have to link the project with LibLAS. See the compilation instructions:
http://www.cloudcompare.org/doc/wiki/index.php?title=Compilation#.5BOptional.5D_Setup_for_LibLAS_support

**Comment by fangxu622** [comment]
![1](https://cloud.githubusercontent.com/assets/16681534/12326478/02acf2d2-bb0c-11e5-9e88-ffdc4caaa7c7.png)
![2](https://cloud.githubusercontent.com/assets/16681534/12326481/09ed26ac-bb0c-11e5-96e3-fd50cd0c09d1.png)
 
![3](https://cloud.githubusercontent.com/assets/16681534/12326715/6a408548-bb0d-11e5-85a1-fa7631595566.png)
![5](https://cloud.githubusercontent.com/assets/16681534/12326723/70956210-bb0d-11e5-996f-b0ee33d11060.png)
![4](https://cloud.githubusercontent.com/assets/16681534/12326730/76afda4a-bb0d-11e5-8c8c-9abddf302173.png)
![6](https://cloud.githubusercontent.com/assets/16681534/12326738/7be8e934-bb0d-11e5-9ab1-c0c42333d357.png)

I don't know which lib have problem ,and which library should add.,

Domestic few people understand CC,your anwser and advice gave me continue to study the confidence of the CC.

**Comment by cloudcompare** [comment]
You can compile each project separately (right click and click on "build"). For a first test, do it in the following order:
- CC_CORE_LIB
- CC_FBO_LIB
- GLEW_LIB
- QCC_DB_LIB
- QCC_GL_LIB
- QCC_IO_LIB
- CloudCompare

And once any of these projects give an error, paste the Visual console here.

**Comment by fangxu622** [comment]
CC_CORE_LIB     OK!
CC_FBO_LIB        OK!
GLEW_LIB            OK!
QCC_DB_LIB         OK!
QCC_GL_LIB          OK!
QCC_IO_LIB           OK!
CloudCompare     Problem,as show in figure:

2>ccCommandLineParser.obj : error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: static enum CC_FILE_ERROR __cdecl FileIOFilter::SaveToFile(class ccHObject *,class QString const &,struct FileIOFilter::SaveParameters &,class QString)" (__imp_?SaveToFile@FileIOFilter@@SA?AW4CC_FILE_ERROR@@PEAVccHObject@@AEBVQString@@AEAUSaveParameters@1@V4@@Z)，该符号在函数 "protected: static class QString __cdecl ccCommandLineParser::Export(struct ccCommandLineParser::EntityDesc &,class QString,class QString *,bool)" (?Export@ccCommandLineParser@@KA?AVQString@@AEAUEntityDesc@1@V2@PEAV2@_N@Z) 中被引用
2>mainwindow.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: static enum CC_FILE_ERROR __cdecl FileIOFilter::SaveToFile(class ccHObject *,class QString const &,struct FileIOFilter::SaveParameters &,class QString)" (__imp_?SaveToFile@FileIOFilter@@SA?AW4CC_FILE_ERROR@@PEAVccHObject@@AEBVQString@@AEAUSaveParameters@1@V4@@Z)
2>ccCommandLineParser.obj : error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: static class QSharedPointer<class FileIOFilter> __cdecl FileIOFilter::GetFilter(class QString,bool)" (__imp_?GetFilter@FileIOFilter@@SA?AV?$QSharedPointer@VFileIOFilter@@@@VQString@@_N@Z)，该符号在函数 "protected: bool __cdecl ccCommandLineParser::saveClouds(class QString,bool)" (?saveClouds@ccCommandLineParser@@IEAA_NVQString@@_N@Z) 中被引用
![11](https://cloud.githubusercontent.com/assets/16681534/12328018/78c8bd4a-bb14-11e5-9e16-ecf403303af0.png)
![22](https://cloud.githubusercontent.com/assets/16681534/12328023/804a44a8-bb14-11e5-8719-11ef55926d1b.png)
![33](https://cloud.githubusercontent.com/assets/16681534/12328025/840ea548-bb14-11e5-8d11-8b8b5527c176.png)
![44](https://cloud.githubusercontent.com/assets/16681534/12328031/8907b31e-bb14-11e5-9077-56ba4c162149.png)
![55](https://cloud.githubusercontent.com/assets/16681534/12328033/8e9d3268-bb14-11e5-8572-b83c465cfa08.png)

**Comment by cloudcompare** [comment]
Are you sure that QCC_IO_LIB compiles properly? Because all the missing links are from this library...

**Comment by fangxu622** [comment]
![111](https://cloud.githubusercontent.com/assets/16681534/12328421/51afc86e-bb16-11e5-9884-f13b5ad94cae.png)
![222](https://cloud.githubusercontent.com/assets/16681534/12328425/5705be68-bb16-11e5-9659-09fa45389643.png)
![333](https://cloud.githubusercontent.com/assets/16681534/12328428/5c09af46-bb16-11e5-916d-62cf5c44308a.png)
![444](https://cloud.githubusercontent.com/assets/16681534/12328522/a559d4aa-bb16-11e5-850f-8c50f2fd1e63.png)
![555](https://cloud.githubusercontent.com/assets/16681534/12328558/d0d4c7de-bb16-11e5-8d6f-5e1f837865cb.png)

![666](https://cloud.githubusercontent.com/assets/16681534/12328704/84ff0ee0-bb17-11e5-851f-637661fc8712.png)

I am also very confused, before you let me order compilation, QCC_IO_LIB cannot pass, but now can pass, cloudcompare still can't pass

**Comment by fangxu622** [comment]
![00000](https://cloud.githubusercontent.com/assets/16681534/12328976/f4a1291c-bb18-11e5-914b-b573f4a2459f.png)

**Comment by cloudcompare** [comment]
And you managed to compile with no INSTALL_XXX_OPTION or WITH_XXX_OPTION? (the minimal CloudCompare setup).

Can you fall-back to this state and then add each option independently (and try to compile each time)?

**Comment by fangxu622** [comment]
![1](https://cloud.githubusercontent.com/assets/16681534/12329252/709978ca-bb1a-11e5-87ee-afa69986ffa3.png)
![2](https://cloud.githubusercontent.com/assets/16681534/12329269/81e28e32-bb1a-11e5-9f72-deb928dde197.png)
![3](https://cloud.githubusercontent.com/assets/16681534/12329274/868e9b38-bb1a-11e5-9895-20423891101d.png)
![4](https://cloud.githubusercontent.com/assets/16681534/12329279/8ae3af3e-bb1a-11e5-8fe3-cca72d8149a2.png)

**Comment by cloudcompare** [comment]
Yes, restart from zero and add the options and plugins one by one in CMake. And try to compile each time. Then we should spot what is causing this issue.

**Comment by fangxu622** [comment]
First configure
![image](https://cloud.githubusercontent.com/assets/16681534/12329721/940d38da-bb1c-11e5-8caf-6d4707829c09.png)
NOW, add
![image](https://cloud.githubusercontent.com/assets/16681534/12329741/ac4ca976-bb1c-11e5-8f03-95c570126af1.png)

![image](https://cloud.githubusercontent.com/assets/16681534/12329728/9aec7d6e-bb1c-11e5-9c71-1c357d358d22.png)

any problem?

**Comment by cloudcompare** [comment]
No I mean, uncheck all the 'OPTION_XXX' and 'INSTALL_XXX' options in CMake. Then configure and try to compile with Visual --> it should work.

Then add one option (for instance 'OPTION_USE_LIBLAS') and then configure, then try to compile with Visual --> does it work? If yes add another option and so on. Until you encounter an issue with Visual.

**Comment by fangxu622** [comment]
i'm trying, add a OPTIONG_VISUAL_LEAK_DETECTOR,
CC_CORE_LIB
CC_FBO_LIB
GLEW_LIB
QCC_DB_LIB
QCC_GL_LIB
QCC_IO_LIB

STILL ok

Cloudcompare compiling

**Comment by cloudcompare** [comment]
Okay, when you'll find the option that cause the issue then tell me.

**Comment by fangxu622** [comment]
unblievable! cloudcompare pass!!!  that why , i just add  OPTIONG_VISUAL_LEAK_DETECTOR,,then configure, and compile with visual studio.......So,how to do next?

**Comment by fangxu622** [comment]
![image](https://cloud.githubusercontent.com/assets/16681534/12330656/393a29ae-bb21-11e5-9fbc-90d6ec680018.png)

**Comment by cloudcompare** [comment]
That's odd... but still a good news.

Now you can try to compile the 'BUILD' project (or the 'INSTALL' one - it's almost the same but the second one copies all the files together and therefore BUILD must be successful first).

**Comment by fangxu622** [comment]
first build ALL_BUILD?  if success, then build INSTALL?

**Comment by cloudcompare** [comment]
Yes. But in fact INSTALL automatically calls ALL_BUILD. But it's better to go step by step in case errors occur.

**Comment by fangxu622** [comment]
build success,now.........new problem , when I open LAS file with CC.exe ,  it will be collapse,
![image](https://cloud.githubusercontent.com/assets/16681534/12331379/2fc236a2-bb24-11e5-85ab-96315595b249.png)

**Comment by cloudcompare** [comment]
Do you start the exe file that has been generated in the installation directory?

**Comment by fangxu622** [comment]
yes,

![image](https://cloud.githubusercontent.com/assets/16681534/12331469/9e9954e8-bb24-11e5-887e-997d1fe846af.png)

**Comment by cloudcompare** [comment]
Then you can try to compile in DEBUG mode first. This will help spot where the issue comes from.

**Comment by fangxu622** [comment]
For the moment, only the release version of CloudCompare supports LibLAS files.......
this means debug version doesn't open las file. right?

**Comment by cloudcompare** [comment]
Yes but you'll only use it to understand why CC crash at startup ;)

**Comment by fangxu622** [comment]
now ,i 'm rebuilding it in debug,x64.........My purpose is to hope to be able to open the LAS files,  with my compiled..

**Comment by cloudcompare** [comment]
By the way have you tested with the official release already? Does it starts normally?

**Comment by fangxu622** [comment]
![image](https://cloud.githubusercontent.com/assets/16681534/12332022/35d3364c-bb27-11e5-8b1e-612f5aaf4a67.png)
I installed it on my PC  ,and work normally,it all can open las file,
![Uploading 4567.png…]()


CC is a very powerful software, very very good 
Thank  all for developing it

**Comment by fangxu622** [comment]
![4567](https://cloud.githubusercontent.com/assets/16681534/12332214/32f5060c-bb28-11e5-8127-1ddb8a0903d4.png)

**Comment by cloudcompare** [comment]
Ok. The 64 bits version of the official release is compiled with Visual 2012. But the 32 bits one is compiled with Visual 2010 and it usually works well.

**Comment by fangxu622** [comment]
ok, i understand ,now i should study how to use CC better,,,,,then devolping it on pcl,...my study task..
by the way ,compiled with VS2013 ,ok?

**Comment by cloudcompare** [comment]
Yes it works also with 2013.

**Comment by fangxu622** [comment]
en, If I met again something wrong,then to consult , thanks for your patience to answer.....
your team is nice !
I should go to bed
bye!

**Comment by fangxu622** [comment]
![image](https://cloud.githubusercontent.com/assets/16681534/12332728/27528dbc-bb2b-11e5-9b66-aab9df3bef39.png)
when debug version open las file,

**Comment by cloudcompare** [comment]
Then the debug version works fine... have you compiled it with the same options (apart from LibLAS)?

**Comment by fangxu622** [comment]
no,,,,,added  option_use_liblas,

**Comment by fangxu622** [comment]
compiled with add option_use_liblas

**Comment by cloudcompare** [comment]
and only this option? My aim was to compile the exact same project in Debug mode (no change in the CMake script). And see if it works. Because in debug mode you'll now what component makes CC crash exactly.

Anyway you should go to sleep ;)

**Comment by fangxu622** [comment]
WIN7 64，trunk-master, vs2013 PCL1.72 +QT5 , after compiled success, I met a problem as show in figure,AND Don't open pcd file

![1](https://cloud.githubusercontent.com/assets/16681534/12508264/f5188fa2-c135-11e5-8043-955d4ba60a21.png)
![2](https://cloud.githubusercontent.com/assets/16681534/12508265/f5202a8c-c135-11e5-9bfb-e48d269cc961.png)

**Comment by dgirardeau** [comment]
Have you compiled CC with a dynamic link version of PCL? (i.e. not static).
Then you'll have to make sure that the PCL dlls are next to
CloudCompare.exe (they may not be copied automatically by the CMake script).

2016-01-22 11:29 GMT+01:00 fangxu <notifications@github.com>:

**Comment by fangxu622** [comment]
I have solved it!  http://www.danielgm.net/cc/forum/viewtopic.php?f=13&t=1175
![3](https://cloud.githubusercontent.com/assets/16681534/12510477/14bea6ac-c145-11e5-92ab-1dbfe3321e8c.png)
just as show in figure ,set path invariable for that and add

**Comment by fangxu622** [comment]
when open las file,
the liblas(1.80) compiled succeful with VS2013
![55555](https://cloud.githubusercontent.com/assets/16681534/12511441/554ffb7e-c14c-11e5-9107-9f7477eff53e.png)

**Comment by fangxu622** [comment]
it's release version

**Comment by cloudcompare** [comment]
What is the version of the LAS file? LibLAS can't read 1.3 or 1.4 files (we are going to move to LASlib for this reason).

**Comment by fangxu622** [comment]
I don't know ，BUT I have  installed version 2.62 of CC  in your official website installed，,it was able to open this LAS file
![1223](https://cloud.githubusercontent.com/assets/16681534/12511665/1bef1d9a-c14e-11e5-8cd5-484f7c133847.png)

**Comment by cloudcompare** [comment]
What version of liblas are you using then? The github trunk version?

**Comment by fangxu622** [comment]
libLAS-1.8.0

**Comment by cloudcompare** [comment]
I'm using the same!

**Comment by cloudcompare** [comment]
Exactly I'm using the version of Jul 28, 2014 (https://github.com/libLAS/libLAS/commit/7e734d1d8b8646af073fb07975489fea366fdae3).

**Comment by fangxu622** [comment]
![123](https://cloud.githubusercontent.com/assets/16681534/12528658/142f282c-c1d8-11e5-9f2c-ec21119ac640.png)
trunk 2.62+VS2013 64bit  QT5.5,,,
how do this
![321](https://cloud.githubusercontent.com/assets/16681534/12528669/63700f32-c1d8-11e5-917b-b73ee10ee621.png)

**Comment by cloudcompare** [comment]
You should check your Qt base directory in CMake because it tries to copy the DLL from a path ending with 'msvc2013_64/include/bin' while it should be 'msvc2013_64/bin'. You'll probably have to remove the /include.

**Comment by dgirardeau** [comment]
It's apparently a linking issue with Qt: make sure to use the right version of Qt (between 5.8 and 5.10, I would say as the others have not been tested for a while or have not been tested yet).  And be sure to use the same architecture / compiler as your project (e.g. Visual 2017 and 64 bits).

**Comment by michaelczh** [comment]
> It's apparently a linking issue with Qt: make sure to use the right version of Qt (between 5.8 and 5.10, I would say as the others have not been tested for a while or have not been tested yet). And be sure to use the same architecture / compiler as your project (e.g. Visual 2017 and 64 bits).

Thanks for the prompt reply. I use Visual 2017 but I am not sure whether it is 64 bits (I select **Visual Studio 15 2017 Win64** as generator).

For the Qt, I am using version 5.9.1, and set the path on Cmake. 

> QT5_ROOT_PATH   <- C:/Qt5.9.1/5.9.1/mingwa53_32

it there any wrong?
