### ISSUE TITLE
tracing tool

### ISSUE THREAD

**Issue by luca-penasa** [cloudcompare/trunk#273]
Thanks Daniel for taking care of the code :-)

As you said this breaks the polyline upsampling strategy.. I had to directly call from the tool the picking method of the gl window for being able to do that kind of upsampling. That's why I chosen to modify the code in the gl window and add public methods... As far as I got the alternative is to implement new PICKING_MODEs for the glWindow..

Just finding the nearest point on the cloud cannot correctly work, cause the user traces a straight segment e.g. to identify something that is a straight feature on the cloud from a specific view (maybe it is not from another pov) and he expect the polyline is projected from that point of view.

The nearest neighbor is not constrained in the intersection of the cloud with the plane defined by the two rays of a segment of polyline, thus possibly leading to misplaced polylines vertices. I was really using and needing the tool in this way and I don't think it makes sense to have "upsampling" in other ways... I was also planning to add a free hand tracing mode that should pick a point every n-pixels in glwindow...

As it is now I should implement these two picking modes as PICKING_MODE in the gl window (right?) as a e.g. FREEHAND_PICKING and MULTI_PICKING modes, each requiring a parameter that should be stored in the glWindow0 and also they should keep trace of the last picked point, at least, plus some other methods for pausing the picking operations etc. Or as alternative one could set up a new glWindow mode TRACING_MODE or something similar. 

Anyway, in my opinion, the point is if makes sense to implement new picking modes in the glwindow for such specific tasks or if the tools should be able to call a public pickPoint method of the glwindow and do whatever they want...

Moving the code to glwindow might be the better solution, given other tools may want to use a FREEHAND_PICKING mode which emit itemPicked() at predifined 3d-or-2d intervals, but to me looked like much more invasive, that's why I opted for the public methods solution :-)

well, I really needed that functionality, so if you can help me finding a good solution I'll be glad to try to implement that.

any other solution I am missing?
what do you think?

Thanks for your work as always! 
Luca

**Comment by cloudcompare** [comment]
Yes, I realized that picking the points is not equivalent to getting the nearest point. But it was so late that I had to stop.

In fact you don't need to ask the GL window to do the picking. This picking process doesn't really concern the window (the window simply needs to give you the viewing parameters and you can publicly access to them).

You can call the picking method on the clouds directly (pretty much in the same way as the window does it). This is why I moved the methods to ccPointCloud and ccMesh.

And in effect to do what you want:
- either you do it on the fly (i.e. each time a new segment is defined). It would allow the user to change the 'oversampling' parameter on the fly depending on whether he picks long segments or small ones. But it could be slow if the oversampling parameter is very big.
- or you can store the viewing parameters for each segment (two matrices and one viewport array) and then you can call the point picking algorithm at the end, segment by segment, in the same way as before (but without any modification to ccGlWindow).

I intended to do it myself (so as to 'restore' the initial behavior).

**Comment by luca-penasa** [comment]
mmmh... the problem is that it would be better to not restrict the picking of the "upsampled" points to the cloud that itemPicked identified as the pertinent one - two consecutive vertices can have two differnent pertinent clouds also - ... the additional points between two vertices can project on totally different clouds (or even mesh in a future).... Thus one would need to actually go trough all the entities again, checking all the possible intersections...

As you say you just need the matrixes of the viewing parameters, but you would end up replicating the same code that is well written in the glWindow class... (?)

Storing the viewing parameters together with each 2d polyvertices would be great I suppose, cause one would be able to reproject the same 2d/3d polyline on a completely different scene... a good thing for having replicability of the algorithms.

What do you think?

**Comment by cloudcompare** [comment]
Oh you don't need to restrict anything for the 'upsampled' picked points. You do exactly the same as the GL window (i.e. process all visible entities). But it's not the same code, it's even simpler (because you only consider the point clouds in your tool). And you don't need to propagate any signal, etc. The replication would be quite limited (well... we'll see ;).

And I just want to store the matrices in your tool (not in the ccPolyLine structure ;). As you have noticed my aim is to minimize the modification of general structures for a single purpose/tool ;)

I'll give it a shot with the matrices stored for each segment and you'll be able to assess if it's the same as before or not.

**Comment by luca-penasa** [comment]
great! thank you!
cause well... I would not be sure where to start :-)

**Comment by luca-penasa** [comment]
still thinking about this... well the procedure of going from the 2d to the 3d for a picked point is really the same, I really cannot see any good reason for duplicating it. Next when we will add picking abilities on mesh we will need to change both the implementations to take care of meshes...

For signal propagation etc... a public method can be simply added to glwindow without emitting signals etc and then another one can be protected or private emitting the signal, as I did with my first commit...

Well... you know what is better in general for cc...

**Comment by luca-penasa** [comment]
Maybe I ended up with a good solution... Why not moving the intersection related stuff toccdbroot? It should go trough the entities and intersect the bounding boxes ... As you said it has not too much to do with the to window...

**Comment by cloudcompare** [comment]
Ok I updated the tracing tool in a minimal way for now. But I modified the general 2D/3D conversion code to get a simpler syntax (as it used in a lot of classes).

I keep your idea of moving the general picking code to the database (or to an external class in fact) but I'll wait that we generalize the tracing tool to meshes (this way the code of the GL window and the one of the tracing tool will be more alike).

**Comment by luca-penasa** [comment]
Great Daniel!
thank you again... I'll try it out!

**Comment by luca-penasa** [comment]
It works great 

the only problem I've seen so far is that if you do a change of view during tracing the segment interested by the change of view will do strange things (not sure if this happens only in upsampling mode):

![tmp](https://cloud.githubusercontent.com/assets/2051141/12673210/9e6451aa-c67b-11e5-9a12-87d2f110c934.png)

this was made with snap to 1 and oversampling to 10, changing the view in the middle...

When using an high snap (like the default 5) the polyline comes out really zig-zagged, so I would suggest to decrease the default snap to 1, or save the latest value...

![tmp2](https://cloud.githubusercontent.com/assets/2051141/12672796/0da9a482-c679-11e5-8177-9f783a01f69a.png)

I'll let you know if I'll notice any other thing!

**Comment by cloudcompare** [comment]
Ok I removed the dependency between the 3D view and the 'snap' field (I initially misunderstood its purpose - it is only useful for the oversampling in fact).

And for the weird behavior of the oversampling, it depends on how you played with the camera but it can also pick a point far behind if the 2D interpolated source falls exactly in front of a hole. But of course there might be other issues ;)

**Comment by cloudcompare** [comment]
Then default snap value has been decreased to 1.
