### ISSUE TITLE
Unused expression

### ISSUE THREAD

**Issue by asmaloney** [cloudcompare/trunk#277]
I'm fixing a bunch of compile warnings and ran across this one in **ccSectionExtractionTool.cpp** in *ccSectionExtractionTool::unfoldPoints()* (around line 1700).  

```cpp
CCVector3 C = box.minCorner();
C.u[vertDim] = 0;
box.minCorner().u[xDim]; //we start at the bounding-box limit
for (unsigned i=0; i<unfoldedCloud->size(); ++i)
{
   //update the points positions
   *const_cast<CCVector3*>(unfoldedCloud->getPoint(i)) = unfoldedPoints[i] + C;
}
```

The line with the comment `//we start at...` is an expression that doesn't do anything.  Was this supposed to be assigned to something?  Is `i` supposed to start at that value? Or is it cruft from an experiment?

**Comment by cloudcompare** [comment]
Oups... It was probably the coordinate of C along the 'xDim' dimension. I'll fix this asap, thanks.
