### ISSUE TITLE
Incorrect printf param

### ISSUE THREAD

**Issue by asmaloney** [cloudcompare/trunk#284]
In **ccPointListPickingDlg.cpp**'s *ccPointListPickingDlg::exportToASCII()* function:

```cpp
	//starting index
	int startIndex = startIndexSpinBox->value();

	for (unsigned i=0; i<count; ++i)
	{
		assert(labels[i]->size() == 1);
		const cc2DLabel::PickedPoint& PP = labels[i]->getPoint(0);
		const CCVector3* P = PP.cloud->getPoint(PP.index);

		if (format == PLP_ASCII_EXPORT_IXYZ)
			fprintf(fp,"%i,",i+startIndex);
```

The `%i` is incorrect here.  `(unsigned int) + (int) == (unsigned int)`.

So, if *startIndex* can be negative and the intent is to allow negative numbers in this printf, then that's a bug and the `i+startIndex` expression needs to be modified to produce a reasonable int.

If *startIndex* can't be negative, then it should be made `unsigned int` and the `%i` should be `%u`.

**Comment by cloudcompare** [comment]
Indeed the startIndex is not negative. It's just that all Qt widgets return 'int' values by default.

Therefore we should indeed cast to unsigned.

**Comment by asmaloney** [comment]
OK - do you want me to submit a PR or do you want to just fix it?

**Comment by cloudcompare** [comment]
I'll do it!
