### ISSUE TITLE
Testing Examples

### ISSUE THREAD

**Issue by asmaloney** [cloudcompare/trunk#305]
It would be useful for testing if we had a set of example files to load - at least one of each format CC supports.  Maybe in a separate "CloudCompare Example Files" repo?

They don't have to be fancy, but it would also be a good place to put edge-cases that have caused problems.

**Comment by cloudcompare** [comment]
Good idea. I already have this kind of dataset. However I'm concerned about the size of some files. I'll try to squeeze them (we won't be able to test the issues with very big files anyway :D).

**Comment by asmaloney** [comment]
Maybe put smaller ones in this set and larger ones in a zip file on Google Drive or something.  Then just put a link to the file in the repo's Readme?

**Comment by ORNis** [comment]
https://git-lfs.github.com/
github support that thing now.

**Comment by asmaloney** [comment]
Cool :+1:

**Comment by cloudcompare** [comment]
Why not. But the big ones are really big (3.3 Gb, and they are not public).
