### ISSUE TITLE
Exception when importing e57-file - E57_ERROR_DUPLICATE_NAMESPACE_PREFIX

### ISSUE THREAD

**Issue by tothom** [cloudcompare/trunk#327]
Hi

I get an error message when I open e57 files. The file is made by CloudCompare itself so it is strange that it cannot open it with CloudCompare. Anybody had this error before?

This is the messages from the console:
```
[14:10:20] [E57] LibE57 has thrown an exception: namespace prefix already defined (E57_ERROR_DUPLICATE_NAMESPACE_PREFIX)
[14:10:20] An error occurred while loading 'Colosseum_chunk 3 - Ready': the third-party library in charge of saving/loading the file has thrown an exception
```

Regards,
Thomas

**Comment by cloudcompare** [comment]
Can you share the file maybe?

**Comment by tothom** [comment]
Sure:

[https://www.dropbox.com/s/6wrgbaofimvseue/Colosseum_chunk%203%20-%20Ready.e57?dl=0]

**Comment by tothom** [comment]
By the way, I tried to open it on another computer where I just installed CC, and I got the same error...

**Comment by cloudcompare** [comment]
I guess the file must be corrupted. I'll check it (then we'll have to understand how it happened).

**Comment by tothom** [comment]
I can open it and index it in Autodesk Recap and import it in Revit or Rhino, without an error message... (Maybe some points are ignored then?)

**Comment by cloudcompare** [comment]
I guess they either don't use LibE57 (the library that do all the job and that sends the error in this case). Or a patched version...

**Comment by cloudcompare** [comment]
Oh that was a silly issue. Not sure why but with this file libE57 throws an exception / error while it's only a minor warning... I've simply ignored this particular 'E57_ERROR_DUPLICATE_NAMESPACE_PREFIX' error code. Do you compile on your side or do you need a new beta version?

**Comment by tothom** [comment]
Hi, great that you found out. I have only successfully compiled something once in my life, so a would appreciate a precompiled beta version.

**Comment by cloudcompare** [comment]
Okay it's online now (the latest 2.6.3.beta version has just been updated)
