### ISSUE TITLE
las/laz reading failures

### ISSUE THREAD

**Issue by quimnuss** [cloudcompare/trunk#353]
Most of the las samples from http://www.liblas.org/samples/ can't be loaded into cloudcompare.

'the third-party library has failed to perform the operation'

Does cloudcompare only support las 1.1?

On ubuntu trusty, tried the latest beta release as well (2.6.3)

**Comment by dgirardeau** [comment]
Well, we do use liblas to do the job. I hope it can handle its own example files ;).

And I was able to load LAS files up to version 1.3 on Windows (with liblas 1.6).

I'll check the samples tomorrow and tell you exactly which ones work and which don't.

**Comment by quimnuss** [comment]
I might have overstated the issue... Apologies! The problem seems to be related to laz, not las. 

e.g. An error occurred while loading 'LAS12_Sample_withRGB_Quick_Terrain_Modeler': the third-party library in charge of saving/loading the file has failed to perform the operation

The las, however, loads fine.

You do ship laszip with cloudcompare right? Just to rule out an issue with my system. 

How can I find out which las version is a file? All this started because I have a las file I can't read... It might be las 1.4 given the error... 

I tried the following files:
mars-wrote-this-vertical-datum-survey-ft-geotiff-keys.las -- read!
IowaDNR-stippled-overlap1.las -- read!
IowaDNR-CloudPeakSoft-1.0-UTM15N.laz
IowaDNR-stippled-overlap.laz
LAS-1.3-waveform-terrapoint.laz
libLAS_1.2.las -- read!
lt_srs_rt-qt-1.1.las -- read!
lt_srs_rt-qt-1.1.laz
srs.las -- read!
st-helens.las -- read!
xyzrgb_manuscript-qt-las1.1.laz
xyzrgb_manuscript.laz

also tried:
las14_type7_fugro_sample.las
kas13.laz

**Comment by ORNis** [comment]
The package use libs from the repos 
http://packages.ubuntu.com/search?keywords=liblas&searchon=names&suite=trusty&section=all
laz is not supported I think.

**Comment by cloudcompare** [comment]
Indeed, on Windows we compile liblas with laszip (we manually add the option).

**Comment by ORNis** [comment]
Contrary of what I have advertised in CC forum or elsewhere, laz is not supported by the package
the Liblaszip is not in Ubuntu/Debian repos, (as we try to rely **only** on libs distributed by Debian/Ubuntu for the package).

**Comment by quimnuss** [comment]
Yes, laszip is not on the repositories. Thanks for the infos cloudcompare, everything is much clear now. And congratulations for the software, it is very well done.

Is it possible to add the laszip support if I compile from source? I presume that if I compile liblas with laszip and then link to it with the liblas option the feature will be supported. Correct? 

Just a head's up: Do you use the c++ laszip interface or the laszip_api ? Because Martin will remove the c++ interface soon. I guess if you use the liblas wrapper you'll be fine.

**Comment by ORNis** [comment]
You are correct for the compilation part.

**Comment by cloudcompare** [comment]
We don't 'use' LASzip, liblas does. We only compile / link liblas with LASzip.

**Comment by quimnuss** [comment]
Thanks to all for the prompt response.
