### ISSUE TITLE
Setting scale does not update transformation

### ISSUE THREAD

**Issue by jo-chemla** [cloudcompare/trunk#354]
Hi, 
The ability to export transformation (from Translation/Rotation and automatic Registration) is a very useful feature. However, when I apply scale to a point cloud through Multiply/Scale (keeping in place or not), the Rigid Transformation Matrix is not updated. This would be a very useful feature as well !
Thanks

**Comment by cloudcompare** [comment]
Oh, you mean the scale is not applied to the history matrix? It's an omission indeed...

**Comment by cloudcompare** [comment]
Ok that's fixed. It will be available in the next release (soon).

**Comment by jo-chemla** [comment]
Yep that was it thanks a lot !

**Comment by jo-chemla** [comment]
I forgot to say that the scale is not applied in the history matrix either if you chose 'Registration/Match scale'. Should I open a new issue ?

**Comment by cloudcompare** [comment]
No it's okay I'll fix this.

**Comment by cloudcompare** [comment]
Ok that's fixed (and same thing for the translation option)

**Comment by jo-chemla** [comment]
Alright, thanks again for your quick replies and edits !
