### ISSUE TITLE
Feature : Color correction

### ISSUE THREAD

**Issue by jo-chemla** [cloudcompare/trunk#355]
A nice feature would be to add ability to use color correction on point clouds (registered clouds). If they are aligned via ICP,  one can just match the colors (RGB) of closest points to apply global color transformation. Thanks a lot !

**Comment by cloudcompare** [comment]
Isn't it already what the 'Interpolate colors from antoher entity' does? See http://www.cloudcompare.org/doc/wiki/index.php?title=Colors%5CInterpolate_from_another_entity.

Or did I misunderstood something?
