### ISSUE TITLE
Red / cyan anaglyph 3D reversed?

### ISSUE THREAD

**Issue by foobarbecue** [cloudcompare/trunk#356]
Hello, I'm trying to use the red / cyan anaglyph 3D with [these 3D glasses]( http://amzn.com/B004HN2U7W). It works well if I turn the glasses upside down. When the glasses are worn normally (correct side up), the left eye is red and the right eye is cyan. It seems the red and cyan on the screen are swapped. I couldn't find an option anywhere to swap the colors.

**Comment by cloudcompare** [comment]
Indeed, this shouldn't be too hard.

I'll try to update this before the next release.

**Comment by cloudcompare** [comment]
Okay the next version will handle the 'cyan / red' and 'cyan / blue' glasses.
