### ISSUE TITLE
Poisson reconstruction level counter does not increment

### ISSUE THREAD

**Issue by foobarbecue** [cloudcompare/trunk#358]
When using the PoissonRecon plugin, a dialog box appears which says "Reconstruction in progress level: n" where n is supposed to be the current octree level of processing. In fact, when I run this, n is always the maximum level.

**Comment by cloudcompare** [comment]
Indeed, this is how Poisson Reconstruction works: it builds an adaptative octree down to a maximum 'level' (how deep it will go depends on the local density). Then it reconstructs the surface.

The level is only displayed here for information purpose. The library doesn't give any progress indicator. This is why the progress bar is in 'infinite mode' (it should freely spin until the process is finished).
