### ISSUE TITLE
Multiple Distance Scalar Fields

### ISSUE THREAD

**Issue by tolgabirdal** [cloudcompare/trunk#361]
I guess a very useful tool would be to export individual components of the scalar fields in one csv file. This could involve 3 columns such as X Y Z. It really eases the usage of the user interface, compared to having to export 3 times to 3 different files.

**Comment by cloudcompare** [comment]
Not sure to understand.

You can generate multiple distance scalar field (you may have to rename the last generated scalar-field to avoid it being overwritten). Or you can also generate 3 SFs at once with the 'split distance' option.

And anyway, when you have multiple SFs on a cloud, if you export it as an ASCII file you'll find all SFs with one column per SF.

Or did I misunderstood something?
