### ISSUE TITLE
Point List Picking is inactive

### ISSUE THREAD

**Issue by asmaloney** [cloudcompare/trunk#370]
From @mankoff #223 

> 2) Point List Picking is inactive, so I can't test this.

I can't reproduce this.  I did the following:

- opened a point cloud
- selected the cloud in the DB Tree on the left
- chose **Point list picking** from the **Tool** menu
- selected some points

Can you give me any more information to try to reproduce it?

**Comment by mankoff** [comment]
Using bunny (see #369) point list picking is available. I can't pick anything (just like #369), but the dialogs work.
