### ISSUE TITLE
Toolbar dragging craziness

### ISSUE THREAD

**Issue by asmaloney** [cloudcompare/trunk#372]
From @mankoff #223 

> 4) If I drag a toolbar to reposition it, the entire CC window shrinks to 1/4th of my monitor and jumps all over the place.

I can reproduce this.  Probably some funkiness going on with the Qt5 change in 2.7.

@cloudcompare & @ORNis - have you guys seen this on your builds?

**Comment by cloudcompare** [comment]
1/4th looks like a Retina issue again (not sure about the jumps ;).

**Comment by asmaloney** [comment]
No - I can reproduce this on my machine.  Dragging dock widgets makes everything get funky.

**Comment by ORNis** [comment]
Ok, @asmaloney  confirmed on my MBP 13 (non retina).

**Comment by asmaloney** [comment]
Some more info on this in case anyone else is trying to work on it (hopefully!):

If you drag a toolbar to one of the QMainWindow toolbar positions it works, but once you drag it over any other element - the 3D view, the DB view, etc. - the window resizes and moves.
