### ISSUE TITLE
Compilation failed in VS2015+QT5.6

### ISSUE THREAD

**Issue by nuli0355** [cloudcompare/trunk#383]
2>D:\SoftWare\VS2015\VC\include\ratio(111): error C2065: “INTMAX_MAX”: Undeclared identifier (Compile the source file D:\SoftWare\cloudcompare\trunk-master\trunk-master\CC\src\DgmOctree.cpp)
2>  D:\SoftWare\VS2015\VC\include\ratio(123): note: Refer to the class being compiled template Examples of “std::ratio<_Nx,_Dx>”References (Compile the source file D:\SoftWare\cloudcompare\trunk-master\trunk-master\CC\src\DgmOctree.cpp)

thank you very much！

**Comment by cloudcompare** [comment]
This may be due to the inclusion of PPL (Parallel Patterns Library)?

You can try to change the [line 23 of SortAlgo.h](../blob/master/CC/include/SortAlgo.h#L23):
```#if (_MSC_VER >= 1800)```
 by
```#if 0```

**Comment by nuli0355** [comment]
thank you!I have solved this problem.
