### ISSUE TITLE
Stuck on Fullscreen (standard fullscreen application mode_ shortcut: F9)

### ISSUE THREAD

**Issue by TheTanay** [cloudcompare/trunk#384]
I was comparing two point clouds (.las files) and wanted to take specif measurement of certain points.
but the point picker dialouge did even not appear and now the cursor simply picks the ponts. I am able to rorte, pan & zoom the couds freely but ALL option on menu strip & DB Tree are disbled. Even F9, F11 are not working. (I used Windows+D to post this)
I can retart with previous .bin file but I can not even save the current file.
please help !

**Comment by cloudcompare** [comment]
That's odd... Was the application already in fullscreen mode when you started the tool?

I guess you tried to hit the Escape key?

You can use the ALT+F4 shortcut to close the application but you'll lose the data indeed...

**Comment by TheTanay** [comment]
thanks for prompt reply. I started using this software 5 days ago and I am sure I messed up while compairng the clouds. The application was not in full screen mode and I think I have pressed Ecs button to disable the point picker. But the measurement dialouge box did not appear first so I got confused. Any chance I can disable the Point Picking tool without the dialouge box?

**Comment by cloudcompare** [comment]
Sadly, appart from the 'Escape' shortcut (but the dialog needs to be active!) and the dialog button I don't see how you can quit it... Sorry about that.

**Comment by TheTanay** [comment]
Its done! I used "Pick Rotation Center". The Point picker was disabled by that and then I pressed F9. Then I closed the point picking dialouge box. 
now its normal again.
