### ISSUE TITLE
LICENCE issue : (L)GPLv2 and v3 not compatible

### ISSUE THREAD

**Issue by vpicavet** [cloudcompare/trunk#386]
There is a licence problem with CC. 

From what I read in the licence.txt file, CC is mainly under GPLv2, and LGPLv2, strictly sticking to this version.
CGAL is linked for some plugins, and this library is only available under version 3 of LGPL and GPL.

Version 2 and 3 of the GNU licences are incompatible. Therefore in the current situation CGAL cannot be linked to CC.

The usual solution is to change the licence mention to "GPL version 2 or later version", which restores compatibility.

Same problem occurred to PostGIS when we wanted to link it to CGAL : 
https://trac.osgeo.org/postgis/ticket/2515

**Comment by cloudcompare** [comment]
CC is an old project, and it was created a few years before the version 3 of the license was published ;)

But I don't think there is any problem to move forward the references to this license (or more simply to add _or later version_ everywhere as you suggested).

Thanks for the tip.

**Comment by vpicavet** [comment]
adding "or later version" is the best option. However, this should be done with consent from all authors.

**Comment by cloudcompare** [comment]
You realize that it's pretty impossible on an open source project ;).

**Comment by NeroBurner** [comment]
not impossible but tricky. [VLC](http://www.jbkempf.com/blog/post/2012/How-to-properly-relicense-a-large-open-source-project) and [Syncthing](https://forum.syncthing.net/t/syncthing-is-going-to-be-relicensed-as-mplv2/2006) did it for example.
Many emails and/or forum posts were needed

**Comment by cloudcompare** [comment]
Oh, actually we already did it (be emails) and I forgot to close this thread ;).

The file headers have been updated consequently.
