### ISSUE TITLE
Problems with segmentation in Mac OS

### ISSUE THREAD

**Issue by stephaniewxk** [cloudcompare/trunk#397]
When using the segmentation tool in Mac OS system with Retina display, the chosen polygon doesn't segment the right position no matter how I change the viewing projection mode. It always has a offset from the original position.
![image](https://cloud.githubusercontent.com/assets/19727841/15775310/1f29d584-2979-11e6-88c5-cf02dd606eb1.png)

**Comment by ORNis** [comment]
closed as dup of #398.
