### ISSUE TITLE
Using CloudCompare libs in a standalone app: PlyFilter asserts

### ISSUE THREAD

**Issue by vdaanen** [cloudcompare/trunk#399]
Hi,

I'm using CloudCompare for a little project which must process Cloud of Points (standalone app, **no GUI**).
Using PlyFilter to write a file raises an assertion. Inspection of source code shows that in file PlyFilter, function loadFile, line 1623, it is necessary to replace 

```
    ccProgressDialog pDlg(false, parameters.parentWidget);
    if (parameters.alwaysDisplayLoadDialog)
    {
```   
by 
```
if (parameters.alwaysDisplayLoadDialog)
    {
        ccProgressDialog pDlg(false, parameters.parentWidget);
```

to avoid assertion.

V

**Comment by dgirardeau** [comment]
Where does it assert?

But you can make a pull request, no worry ;)

**Comment by vdaanen** [comment]
In the current source code
```
ccProgressDialog pDlg(false, parameters.parentWidget);
if (parameters.alwaysDisplayLoadDialog)
{
```
assertion occurs when creating pDlg (always created, even if parameters.alwaysDisplayLoadDialog is false)

**Comment by vdaanen** [comment]
Daniel,

I let you decide to apply or not the change proposed above...
V
