### ISSUE TITLE
Proper Syntax for CROP2D from command line (windows)

### ISSUE THREAD

**Issue by OH8HO** [cloudcompare/trunk#404]
I am looking to use crop 2d from the command line and I'm a little off with the syntax. Here's what I'm working with:

CloudCompare  -O -GLOBAL_SHIFT -543600 -4174000 0 C:\path\to\file.las -CROP2D X 4 300 50 300 5 480 5 480 50

after the "-CROP2D" flag, I specify a polygon in the X-plane of 4 vertices, so that I'm only working with northing and elevation values.The Northing values are the 300 and 480 while the elevation values are the 5 and 50. 

The Console reports that the file has been read in and that it has 11 million points but after the cropping it says "no points of cloud fall inside the input box" 

Am I using the proper syntax?

The wiki page says this is the syntax...
-CROP2D {ortho_dim} {n:number of vertices} X1 Y1 X2 Y2 ... Xn Yn

**Comment by cloudcompare** [comment]
You should test the GLOBAL_SHIFT result by saving the resulting cloud in a BIN file for instance (before applying the crop2D tool).

I can't remember but the shift may have to be positive (+543600 +4174000).

**Comment by cloudcompare** [comment]
See 86631f2719f5d47f34c33e50efe315f4477329b3
