### ISSUE TITLE
PCD files not supported in Mac build

### ISSUE THREAD

**Issue by paulrbarnard** [cloudcompare/trunk#405]
According to the documentation .pcd files are supported.  There is no open dialogue filter for Point Cloud Library files and when selecting the file using 'All' the program reports that the file type can not be recognised.  There is a comment on the CloudCompare forum with a fix for the Unix build.

**Comment by asmaloney** [comment]
My CloudCompare releases for the Mac do not support the Point Cloud Library. (Please see #300 - maybe @markweir had some success or you can work together on it?)

Can you please point out the place in the docs where you saw this so we can fix it?

**Comment by paulrbarnard** [comment]
Thank you.  I will take a look at the other issue.

Page 18 of the manual (http://www.danielgm.net/cc/doc/qCC/CloudCompare%20v2.6.1%20-%20User%20manual.pdf) in the supported files section.  I'm assuming there is just the one manual for the product rather than build specific versions.

**Comment by asmaloney** [comment]
Ah, yes - there is only one PDF for all versions.  @dgirardeau will have to weigh in on that.

The specific _plugins_ that are included on the Mac version are on the [Mac CloudCompare release page](https://asmaloney.com/software/).

Some plugins are proprietary, some are Windows only, and some - like the PCL - is just too complicated to build and maintain.  I think there are problems with the PCL pugin on Windows too and PCL itself doesn't seem to be [supported anymore](http://ns50.pointclouds.org/) (last release Oct 2013).

**Comment by paulrbarnard** [comment]
OK.  Seems the last sprint on PCL was completed in 2014.  That's not so long ago.  We have a bunch of in-house tools generating this format so I'll have a quick prod at the code and see if I can get something to build if not I'll jump into Linux as there seems to be a solution on that OS http://www.danielgm.net/cc/forum/viewtopic.php?f=10&t=1687&p=6564&hilit=pcd#p6564 

Many thanks for your help.

**Comment by cloudcompare** [comment]
Indeed, there's only one documentation, and it's based on the Windows version (which has all features, contrarily to the others).

And 2 years for a library is a looooooooong time ;)

**Comment by luca-penasa** [comment]
Maybe this could help:
https://github.com/luca-penasa/minipcl

Not sure it is still working but could be used as submodule in the PCL IO plugin to give IO support. Boost and Eigen maybe are more reasonable deps than the plethora of stuff PCL needs.

Best thing would probably be to implement a standalone reader/writer for PCL files..
