### ISSUE TITLE
GLX startup problem

### ISSUE THREAD

**Issue by jonas-gbl** [cloudcompare/trunk#406]
Hello, 

I tried to re-install on a fresh Arch Linux machine and I get  
`Could not initialize GLX`
`Aborted (core dumped)`

I can find any logs or any useful info. ccViewer runs fine.

**Comment by renatoGarcia** [comment]
I'm using Arch Linux too, and had the same problem. This bug is related to Qt packages upgrading to version 5.7.0. CloudCompare works fine after downgrading Qt to version 5.6.1 and recompiling it.

**Comment by elmuz** [comment]
I am suffering of this too. Hope it will be fixed soon.

**Comment by PabloCOVES** [comment]
Same here on every Arch.
Will try Renato Garcia's solution.

**Comment by areslp** [comment]
Same problem. Solved by renatoGarcia's solution, thanks!

**Comment by elmuz** [comment]
Since I have to update the system for other reasons, has this issue been fixed in the latest commits? Or alternatively, do you know if a there is a safe way in Archlinux to keep the old QT while update some other pkgs? I got a dependencies loop that was driving me crazy... :-(

**Comment by jonas-gbl** [comment]
In `/etc/pacman.conf` add
`IgnoreGroup = qt5`
More info on:
https://wiki.archlinux.org/index.php/Pacman#Skip_package_from_being_upgraded

That's how I solved it temporarily in my system.

**Comment by elmuz** [comment]
I did the same, but it wasn't enough. In my case, the dependencies chain got broken because of package 'texlive-bin' -> which provides 'pdflatex' -> which needs 'poppler-qt5' -> which depends on Qt5. I got mad for like 30 mins downgrading all involved packages and I won't update my system until working on this project.

**Comment by jonas-gbl** [comment]
@renatoGarcia Thank you. @elmuz I discovered I had the same issue. Texmaker wouldn't start. After the fix of @renatoGarcia, using PKGBUILD by @nine7nine:
https://github.com/nine7nine/CloudCompare-Archlinux
everything is working and updated.

**Comment by elmuz** [comment]
Thank you @jonas-gbl, I will have a look at it.

**Comment by luca-penasa** [comment]
I exerienced this issue too. I am on an arch-derived distro with qt 5.7. I confirm that one can compile CC with qt 5.6 and that will solve the problem. 
It looks like this is actually a qt bug:
https://bugreports.qt.io/browse/QTBUG-54946?jql=text%20~%20%22Could%20not%20initialize%20GLX%22

as Daniel said, probably a bad conjuction of nvidia+qt5.7, so in such a case just downgrade system qt or install qt 5.6 from the online installer.
