### ISSUE TITLE
Plugin to load new file format

### ISSUE THREAD

**Issue by NeroBurner** [cloudcompare/trunk#416]
Is there a way to extend the file loader with a plugin to support a new filetype. Up until now I converted the file to a csv file and loaded it per drag&drop into CC, where the CSV-import dialogue pops up

I've seen the qKinect plugin is the only one importing a cloud. The other plugins are functions working on the imported clouds.

I've found a rough guide to write a plugin in the [Contributing](https://github.com/cloudcompare/trunk/blob/master/CONTRIBUTING.md#designing-a-new-qcc-plugin) file.

A few other plugin-related questions:
- how can I maintain such a plugin in its own repository. I'd like to avoid to  keep a fork of CC up to date.
- Does a plugin needs to be compiled with the whole CC project or is it possible to compile it independently?

**Comment by cloudcompare** [comment]
Indeed, you can create 'I/O plugins'. They are very simple plugins that return an instance of a child of an implementation of the FileIOFilter class. See how the qCSVMatrixIO plugin works for instance.

And regarding your other questions:
- you can store this plugin (code) in its own repository. Then either clone the repository directly under 'trunk/plugins' (not sure if it's very clean but at least it works on my side ;) or declare it as a submodule
- and yes for now you'll need to compile the plugin with the whole project (_even though an I/O plugin only depends on CCLib and qCC_db_).

**Comment by NeroBurner** [comment]
thanks for the fast reply and pointer to qCSVMatrixIO

> -and yes for now you'll need to compile the plugin with the whole project (even though an I/O plugin only depends on CCLib and qCC_db).

Does that mean if I want to add one plugin to the standard CC-deb installation I need to recompile all plugins or loose functionality?

**Comment by cloudcompare** [comment]
It depends whether you wan't to be sure that everything works or not ;)

For I/O plugins, if the CC_CORE_LIB and qCC_db libraries haven't changed, then you can simply copy your newly compiled plugin in the plugins folder and it will work... But it's always a bit hard to be sure of that...

If you want to be sure that your plugin will work with a given version, then you have to compile it with the same source code (use the tags for that: https://github.com/cloudcompare/trunk/tags).

**Comment by NeroBurner** [comment]
I've downloaded version 2.7.0, extracted the tar.gz file and compiled with
```
mkdir build
cd build
cmake -DINSTALL_QCSV_MATRIX_IO_PLUGIN=ON ..
make -j4
```
It compiled without errors :+1: 
I started it with
```
./qCC/CloudCompare
```

Which also started without problems, another :+1: 

My Problem is, that the CSVMatrixIO Option does not show in the File - Open Dialogue. The Plugins menu entry is also grey. I confirmed, that the plugin was built, but it seems to me, that it does not get loaded

**Comment by cloudcompare** [comment]
I believe you should compile the 'INSTALL' target (something line 'make INSTALL ...')

**Comment by ORNis** [comment]
yes. 
make install

**Comment by NeroBurner** [comment]
thanks a lot! it worked! :+1: 

made a copy of the CSV Matrix IO plugin and renamed all occurrences of CSV Matrix with MyFormat and it works :)

```
cmake -DINSTALL_QCSV_MATRIX_IO_PLUGIN=ON -DINSTALL_QMYFORMAT_IO_PLUGIN=ON -DCMAKE_INSTALL_PREFIX=package .. && \
make -j8 && \
make install
```
