### ISSUE TITLE
Abort on moving BubbleView Mode

### ISSUE THREAD

**Issue by NeroBurner** [cloudcompare/trunk#418]
Running on Ubuntu 16.04
When entering BubbleView Mode and Immediately using the right mouse button to move the camera CloudCompare 2.7.0 closes and shows the following Message
```
CloudCompare: /home/gc/repos/CloudCompare/CloudCompare/libs/qCC_db/ccIncludeGL.h:80: static ccGLMatrixd ccGL::Frustum(double, double, double, double, double, double): Assertion `znear > 0' failed.
Aborted (core dumped)
```

When doing the same thing in 2.6.3 the view just turns black. Leaving the BubbleView Mode makes the cloud reappear and one can enter BubbleView Mode once again

A way to prevent the abort (or black screen) is (during BubbleView Mode) to zoom in with the middle mouse wheel and zoom out again. Then the camera can be moved without a problem

Way to reproduce:
- (optional): load a pointcloud
- hit 'B' to enter BubbleView Mode
- click and hold the right mouse button and move the mouse

**Comment by cloudcompare** [comment]
I acknowledge the issue! I'll try to fix it asap.

Thanks for the feedback.

**Comment by cloudcompare** [comment]
Ok that's fixed. It was due to the fact that the default FOV for the Bubble View mode (when no sensor is found) was 90 degrees, and ccGLWindow was internally relying on a value based on tan(FOV) = tan(90) = infinite!
