### ISSUE TITLE
File dialog on KDE

### ISSUE THREAD

**Issue by brothermechanic** [cloudcompare/trunk#421]
Hello
How i can compile CC for more KDE integration, namely file dialog?

**Comment by cloudcompare** [comment]
The only dialog that shouldn't be using the native style is the main file loading one indeed (because of a recurring issue on Windows).

You have to replace ```QFileDialog::DontUseNativeDialog``` by 0 in ````MainWindow::doActionLoadFile``` (in mainwindow.cpp, line 9038).
