### ISSUE TITLE
Extend PoissonRecon's UI controls

### ISSUE THREAD

**Issue by Jean-Roc** [cloudcompare/trunk#423]
Hi,

Would it be possible to extend the PoissonRecon's UI with more options to control the output ? The command tool has some interesting commands such as--polygonMesh for an non-triangulated mesh and --aRatio to to discard disconnected islands.

Regards,
JR

**Comment by cloudcompare** [comment]
CloudCompare can't handle non-triangulated meshes (therefore we can't enabled this option).

But the 'aRatio' could be interesting indeed.

**Comment by Jean-Roc** [comment]
Thanks for the answer :) Beside the parameters shown in the UI, is the plugin using some of the others with default values behind the scene (such as confidence or nWeights) ?

I ask this question because I would like to try out the quad output with poissonrecon's command line but I would like to have the same parameters than those I use in CC.

**Comment by cloudcompare** [comment]
I believe we were using the default parameters, but something may have changed since then.

You can see all the parameters and there default values here:
https://github.com/cloudcompare/PoissonRecon/blob/master/Src_CC_wrap/PoissonReconLib.cpp#L42

**Comment by cloudcompare** [comment]
I finally had some time to check this 'aRatio' parameter, and it's in fact a parameter of the SurfaceTrimmer part of PoissonRecon (that we don't use).
