### ISSUE TITLE
describe new BIN format on wiki

### ISSUE THREAD

**Issue by maruncz** [cloudcompare/trunk#424]
could you write description of new BIN v2 format on wiki?

i want to be able to load it to my application

**Comment by cloudcompare** [comment]
See http://www.cloudcompare.org/forum/viewtopic.php?t=1864.

Due to it's serialized and versioned nature, the new BIN V2 format cannot be described easily. You have to use QCC_DB_LIB to open a BIN file in another program (mind that this library is GPL).
