### ISSUE TITLE
Wrong title of bilateral filter window

### ISSUE THREAD

**Issue by Remi-C** [cloudcompare/trunk#426]
Hey,
this new bilateral filter feature is absolutely awesome,
I used it extensively, but I had to rely on very slow python (opencv, skimage).

Allow me to point a very small bug : when the filter is being computed, the window showing progress is titled 'Gaussian ...'.
I guess its the remaining of the copy past of the code ;-)

Excellent feature, as usual!
Cheers

**Comment by cloudcompare** [comment]
Ah! In fact this filter is as old as CloudCompare ;). And it does rely on a more simple Guassian filter (this is why you see this progress bar).

But thanks for the feedback, don't hesitate to make similar notifications in the future.
