### ISSUE TITLE
qHoughNormals build failure linux

### ISSUE THREAD

**Issue by nine7nine** [cloudcompare/trunk#433]
hi,

I've been building cloudcompare on Archlinux.Hhowever, the newest plugin; QhoughNormals doesn't seem to want to build;

/home/ninez/github/cloudcompare-git_build/src/trunk/plugins/qHoughNormals/qHoughNormals.cpp: In member function ‘void qHoughNormals::doAction()’:
/home/ninez/github/cloudcompare-git_build/src/trunk/plugins/qHoughNormals/qHoughNormals.cpp:131:25: error: ‘class Eigen_Normal_Estimator’ has no member named ‘maxProgressCounter’
    int maxProgress = ne.maxProgressCounter();
                         ^~~~~~~~~~~~~~~~~~
/home/ninez/github/cloudcompare-git_build/src/trunk/plugins/qHoughNormals/qHoughNormals.cpp:146:7: error: ‘class Eigen_Normal_Estimator’ has no member named ‘setProgressCallback’
    ne.setProgressCallback(progressLambda);
       ^~~~~~~~~~~~~~~~~~~
make[2]: *** [plugins/qHoughNormals/CMakeFiles/QHOUGH_NORMALS_PLUGIN.dir/build.make:72: plugins/qHoughNormals/CMakeFiles/QHOUGH_NORMALS_PLUGIN.dir/qHoughNormals.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1440: plugins/qHoughNormals/CMakeFiles/QHOUGH_NORMALS_PLUGIN.dir/all] Error 2
make: *** [Makefile:128: all] Error 2

It did build with the initial commit, but I guess when the progressbar and sliders, etc were added it stopped building. Here is a more complete output of the plugin building; http://pastebin.com/1vMZby29

thanks, btw ~ great software! :)

**Comment by cloudcompare** [comment]
Have you updated the submodule? (https://github.com/cloudcompare/normals_Hough). Because it has been updated as well.

**Comment by nine7nine** [comment]
Hey, I have now!

In my build script I was using the branch from which you forked your own branch... it looks you just forked the code 5 days ago, I obviously missed the train on that! ;) .. I've updated my build scripts to pull from your branch now. thanks for pointing that out.

I've successfully build the plugin now. thx
