### ISSUE TITLE
Progress Dialog on 2.6.3

### ISSUE THREAD

**Issue by NeroBurner** [cloudcompare/trunk#438]
I want a module to be compilable under 2.6.3 and 2.7. I've written the io module in 2.7 and then tried to compile it on 2.6.3.

I had to remove the ccProgressDialog and wasn't able to find a replacement in 2.6.3

The following code is commented out:
```
	//progress dialog
	ccProgressDialog pdlg(true, parameters.parentWidget);
	CCLib::NormalizedProgress nprogress(&pdlg, root.pointCountTotal/BUFFER_SIZE);
	pdlg.setMethodTitle(QObject::tr("Loading file [%1]").arg(filename));
	pdlg.setInfo(QObject::tr("Points loaded: 0"));
	pdlg.start();
```
and while loading the file
```
		// update the progress info
		pdlg.setInfo(QObject::tr("Points loaded: %1").arg(total));

		if (!nprogress.oneStep())
		{
			//cancel requested
			result = CC_FERR_CANCELED_BY_USER;
			break;
		}
```

Is there a progress dialog in 2.6.3. Without it CloudCompare just seems unresponsive while loading a file

Edit:
As an additional Question: is it possible to distinguish between 2.7 and 2.6.3 at compile time?

I've found `#ifdef CC_QT5` in various 2.6.3 plugins. But this flag has vanished from the 2.7 plugins and is always not defined for me in 2.7

**Comment by cloudcompare** [comment]
Indeed, there has been a lot of modifications with the 2.7 version. There's no more ```CC_QT5``` macro defintion in the 2.7 version, because Qt 4 is no longer supported. But you should be able to use the ```#ifndef CC_QT5``` macro to make the plugin work with both versions.

I'm pretty sure that the ccProgressDialog class was already existing in the 2.6.3 version, but at that time you couldn't create a CCLib::NormalizedProgress instance "on the stack". You had to instantiate it dynamically then (```CCLib::NormalizedProgress* nProgress = new CCLib::NormalizedProgress(&pDlg, ...)`;``).

And CC should totally be able to load a file without any progress notification. There might be another issue here?

**Comment by NeroBurner** [comment]
Yes you are right, CCprogressDialog was there and there was another problem.
CCprogressDialog compiling under 2.6.3 (under trusty Ubuntu 14.04) had the Problem that `QObject::tr("Loading file [%1]").arg(filename)` is not a `const char*`. Compiled under xenial (Ubuntu 16.04) this somehow was not a Problem. I'm now creating the string with the help of std::stringstream. 
But I didn't have to put the CCLib::NormalizedProgress on the heap and it still works
```
//progress dialog
	ccProgressDialog pdlg(true, parameters.parentWidget);
	CCLib::NormalizedProgress nprogress(&pdlg, root.pointCountTotal/BUFFER_SIZE);
	{
		std::stringstream ss;
		ss << "Loading file [" << filename.toStdString().c_str()<< "]";
		pdlg.setMethodTitle(ss.str().c_str());
		pdlg.setInfo("Points loaded: 0");
		pdlg.start();
	}
```
and 
```
		{
			// update the progress info
			std::stringstream ss;
			ss << "Points loaded : " << total;
			pdlg.setInfo(ss.str().c_str());
		}
```

For the Qt4 and Qt5 checks I've borrowed the if that originally defined the CC_QT5 define
```
#if (QT_VERSION < QT_VERSION_CHECK(5, 0, 0))
Q_EXPORT_PLUGIN2(qMYIO,qMYIO);
#endif
```
and
```
#if (QT_VERSION >= QT_VERSION_CHECK(5, 0, 0))
	Q_PLUGIN_METADATA(IID "cccorp.cloudcompare.plugin.qMYIO")
#endif
```

I have tested my plugin on Ubuntu 14.04 with 2.6.3 with Qt4 and Qt5 and On Ubuntu 16.04 with 2.7.0 with Qt5 and it works (after a recompile of course)

Thanks a lot! :+1:

**Comment by asmaloney** [comment]
> I'm now creating the string with the help of std::stringstream. 

Just an FYI - if you want to avoid the extra stringstream stuff you could use something like:

`QObject::tr("Loading file [%1]").arg( filename ).toLatin1().constData()`.
