### ISSUE TITLE
New version of PoissonReconLib fails to compile on ArchLinux

### ISSUE THREAD

**Issue by nine7nine** [cloudcompare/trunk#440]
Hi guys,

I had an issue filed from a user on Archlinux that PoissonRecon was failing to compile. He happened to have pulled from github as changes were being made / it was being updated, so his error wasn't relevant. ** However, I tried to build CC a few hours later and PoissonRecon doesn't build;

http://pastebin.com/YPvRc31q

I may have to just provide a workaround (like using the old version) in my packaging for now.

**Comment by cloudcompare** [comment]
Weird, the automatic gcc compilation works (not the clang one, but for another reason than yours ;).

Looking at the error, is it possible you have updated the repository just between the time I updated PoissonRecon and the time I updated CloudCompare (a little bit later)? Can you try to refresh both projects?

**Comment by nine7nine** [comment]
you may be right, i'll test it out shortly and let you know. thanks

**Comment by nine7nine** [comment]
Hi, grab this source package;

https://github.com/nine7nine/CloudCompare-Archlinux/blob/master/cloudcompare-git-2.6.2.r753.gf78df21-1.src.tar.gz

it should build, as it uses the old version of PoissonRecon... I'll update my repos later, once I have time to test everything with the new poissonreon changes and CC changes.

**Comment by cloudcompare** [comment]
Ok but there was a small bug in the older version of PoissonRecon (it would crash on small clouds).

**Comment by nine7nine** [comment]
Sorry CC, I pasted that last comment (that I then deleted) to the wrong repo/issue... I had too many tabs open... That was meant for an Archlinux user in one of my issue trackers. sorry! ;) ... I'm just providing him with a temp. package to work around his problem, until I can test out the updated CC and PoisonReconLib. 

sorry again, thanks!

**Comment by nine7nine** [comment]
hey CC, 

You can close this issue. I have resolved the build problem, updated my repo/source packages with those changes and additionally have built both gcc and icc builds for archlinux.... it looks like it was just my timing when pulling from github.

everything seems to be okay now. Thanks!

**Comment by cloudcompare** [comment]
No problem ;)
