### ISSUE TITLE
ccViewer only opens all-uppercase files

### ISSUE THREAD

**Issue by Patola** [cloudcompare/trunk#443]
When used from the command line in Linux (Ubuntu 16.04 64 bits), ccViewer only opens the file if it is in all caps. e.g.

`$ ccViewer yodabuddha.stl`
dialog: 

> Error - [Load] File 'YODABUDDHA.STL' doesn't exist!

Hence, it seems to convert the filename to all caps. Probably some wrongful .toUpper(). I have seen that line 192 of ccviewer/main.cpp makes the following comparison:

`                         if (argument.toUpper() == "-WIN")`

Perhaps it is in that part that it screws up the string? In Windows it would not make a difference because it is case-retentive but not case-sensitive.

**Comment by cloudcompare** [comment]
The culprit was another call to 'toUpper':
`QString argument = QString(argv[i++]).toUpper();`

That's fixed now. Thanks for the feedback.

**Comment by Patola** [comment]
Thanks. I found the bug and I was even able to fix it here. But to fix it you should not only change this line. In line 192 it uses .toUpper() to compare to "-WIN", but in line 217 it does not use it. Line 217 should be:
`else if (argument.toUpper() == "-TOP")`

**Comment by cloudcompare** [comment]
See ecd5c880380c7af6ba855729512d93476af7c285
