### ISSUE TITLE
Error box below splash screen on windows

### ISSUE THREAD

**Issue by samthiele** [cloudcompare/trunk#448]
On startup of the latest 2.8-beta build (from the website) a message box appears, but is hidden by the CC splash screen (see image). Should be an easy fix?

The message says "[Gamepad] No device detected", and CC works fine once it is closed.... it's just a bit clumsy/difficult to close when it is behind the splash screen.

![2016-11-07 2](https://cloud.githubusercontent.com/assets/10939946/20042492/f96f780e-a4ce-11e6-8e51-fde4b3940b7e.png)

**Comment by cloudcompare** [comment]
How silly... I fixed this! The online beta version is currently uploaded on the server...
