### ISSUE TITLE
refactoring qCC methods

### ISSUE THREAD

**Issue by Xobile-S** [cloudcompare/trunk#449]
I want to use cross section tool with ‘Export multiple slices' option (ccClippingBoxTool & ccClippingBoxRepeat method) by simply not calling its UI but passing arguments to its functions.
How do I set box thickness fields X,Y,Z based on actual size of point cloud and extract its segments in grid-like pattern ?

**Comment by cloudcompare** [comment]
Refactoring the ```ccClippingBoxTool::extractSlicesAndContours``` method should be easy. I can't convert it to a static method with parameters. And the method will output a group of clouds (and optionally a group of contours).

I'll get back to you when it's done.

**Comment by cloudcompare** [comment]
Oj, it's done. See https://github.com/cloudcompare/trunk/blob/master/qCC/ccClippingBoxTool.cpp#L512.

In effect you have to define a ccClipBox object to define the slice: the dimensions of the slice are set with the ccClipBox bounding-box, and its position and orientation with the 'GLtransformation' member).

You'll probably have to look how all this is used in the existing clipping-box tool to understand how it works.

**Comment by cincinatee** [comment]
can same be done to ApplyTransformationDlg methods?

**Comment by cloudcompare** [comment]
Which method(s) exactly?

**Comment by cincinatee** [comment]
Could it be possible to perform transformations by reading given 4x4v matrices from a specified ASCII file, without the dialouge box ?
Apply Transformation (Ctrl +T) >> Matrix 4x4 >> ASCII file

**Comment by cloudcompare** [comment]
This is already possible with the ```ccGLMatrix::fromAsciiFile``` method.

**Comment by cincinatee** [comment]
thanks!
