### ISSUE TITLE
cloud color changes when using point picking tool

### ISSUE THREAD

**Issue by vinayan** [cloudcompare/trunk#453]
I tried to use the point picking tool on the "CloudCompareGarden1" bin fiiles. As soon as I pick a point, the colors change for the cloud. Is there an option not to lose the existing color information?

Before Picking

![garden1](https://cloud.githubusercontent.com/assets/1298627/20295089/e5ad2a54-ab28-11e6-8fd7-c30304ed14af.png)

After Picking

![garden2](https://cloud.githubusercontent.com/assets/1298627/20295099/f0fadd3e-ab28-11e6-8337-f6b7fd598ba4.png)

**Comment by cloudcompare** [comment]
Yes, this is the point picking debug pattern (only activated in debug mode). You can disable it by commenting the sections between QT_DEBUG macros in '''ccGenericPointCloud::pointPicking''' (ccGenericPointCloud.cpp, lines 387 and 409). And same thing in '''ccOctree::pointPicking''' (lines 577 and 666).

**Comment by vinayan** [comment]
okay..i should have tested it in release before asking here..thank you
