### ISSUE TITLE
the version of QT and openGL

### ISSUE THREAD

**Issue by shloog** [cloudcompare/trunk#471]
## Current Behavior

I want to debug and complie cloudcompare source code from github. How can I know the version of QT、 openGL and others which are relyed by cc. 

## Your Environment

* OS & Version:win10
* CC Version: lateset github version
* Graphics card:

**Comment by cloudcompare** [comment]
According to the BUILD.md file (https://github.com/cloudcompare/trunk/blob/master/BUILD.md) you need Qt 5.5 or newer. The OpenGL stuff is taken care of by Qt (but to run CC your video card will need to support at least OpenGL 2.1 I believe). And for the other libraries (if you compile the plugins and support for some specific I/O formats), it's generally a better idea to use not too old versions.

**Comment by shloog** [comment]
I am building this project with a computer which is installed vs2010 and vs2015 using cmake. when I configure,I specify the generator vs2015 and set "use default native compilers" , then i configure, but it worns that "the c complier is unkown;the c++ compiler is unkown""CMake Error at CMakeLists.txt:15 (project):
  No CMAKE_C_COMPILER could be found."   "CMake Error at CMakeLists.txt:15 (project):
  No CMAKE_CXX_COMPILER could be found."

**Comment by cloudcompare** [comment]
Please try to avoid
