### ISSUE TITLE
problem in building the project in VS2015

### ISSUE THREAD

**Issue by shloog** [cloudcompare/trunk#473]
## Current Behavior

I am building this project with a computer which is installed vs2010 and vs2015 using cmake. when I configure,I specify the generator vs2015 and set "use default native compilers" , then i configure, but it worns that "the c complier is unkown;the c++ compiler is unkown""CMake Error at CMakeLists.txt:15 (project):
No CMAKE_C_COMPILER could be found." "CMake Error at CMakeLists.txt:15 (project):
No CMAKE_CXX_COMPILER could be found."

## Your Environment

* OS & Version:
* CC Version:
* Graphics card:

**Comment by cloudcompare** [comment]
This looks like a CMake problem. Have you tried to remove and reinstall it?

**Comment by shloog** [comment]
Yes ,i just reinstalled cmake,but the same problem

**Comment by shloog** [comment]
Error in configuration process,project maybe invalid

**Comment by cloudcompare** [comment]
Well, this is really a CMake issue anyway, it has nothing to do with CloudCompare. Google is your best friend ;)

**Comment by shloog** [comment]
cmake policies active: CMP0020 CMP0043
The C compiler identification is unknown
The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:15 (project):
  No CMAKE_C_COMPILER could be found.



CMake Error at CMakeLists.txt:15 (project):
  No CMAKE_CXX_COMPILER could be found.



Configuring incomplete, errors occurred!
See also "E:/cloudcompare/trunk-master/newCC/CMakeFiles/CMakeOutput.log".
See also "E:/cloudcompare/trunk-master/newCC/CMakeFiles/CMakeError.log".
