### ISSUE TITLE
Viewports not saved in BIN file

### ISSUE THREAD

**Issue by mankoff** [cloudcompare/trunk#474]
Viewports should be saved in BIN files

## Your Environment
* OS & Version: OS X
* CC Version:  2.8 beta

**Comment by cloudcompare** [comment]
Well they should ;). You just need to select them with the other entities when saving to a BIN file.

Or is this a Mac only issue?!

**Comment by asmaloney** [comment]
Tested and it works on the Mac for me.  Are you sure they are selected when you are saving the BIN?

As I just mentioned to Daniel I find it a little confusing that they are created at the top-level outside the group of the "thing I'm working on" and missed selecting them the first time.

**Comment by mankoff** [comment]
Correct. This is just a Human Error, but helped by the UI. See #476
