### ISSUE TITLE
Add graphical hints to DB Tree

### ISSUE THREAD

**Issue by mankoff** [cloudcompare/trunk#476]
Nested items in `DB Tree` are hard to see. See for example #474. See screenshot of CC. Viewports are **not** nested, but look like they are.

A small visual aid would help. See screenshot of Paraview `Pipeline Browser`

<img width="291" alt="screen shot 2016-11-27 at 09 41 21" src="https://cloud.githubusercontent.com/assets/145117/20649152/48aa0530-b486-11e6-8365-05263dc6d859.png">
<img width="334" alt="screen shot 2016-11-27 at 09 40 32" src="https://cloud.githubusercontent.com/assets/145117/20649154/4bb2bad8-b486-11e6-86bf-be38a5df0eb0.png">

**Comment by cloudcompare** [comment]
Ok that's fixed (5857d1ef1c4b9aca0b43ea79f992d5ffead1363c).

**Comment by cloudcompare** [comment]
This will look like this now: 
![image](https://cloud.githubusercontent.com/assets/2735509/20649597/8aca8cea-b4c3-11e6-83b9-92b105557f0f.png)
