### ISSUE TITLE
apply inverse transformation tick box doesn't work

### ISSUE THREAD

**Issue by Ospeleo** [cloudcompare/trunk#477]
Hi,

Whether or not I check the "apply inverse transformation" tick box in the "apply tranformation" window, CC apply the same transformation

First time I notice this behavior.
I use CC2.8.beta .
New PC laptop that has been running CC for one week on Win10.
works fine on CC2.7 for Mac.

- start CC
- open any .bin file
- select one cloud, translate it with the translation Tools
- copy the transformation matrix that was generated
- click "apply transformation", paste the matrix, select "apply inverse tranformation"
- the original transformation is apply again (not the inverse)

If you need more background, ask me, I don't know what would be relevant.
thanks

**Comment by cloudcompare** [comment]
Have you updated the beta with the latest one?

I believe this bug was fixed a few days ago (note also that a new beta will be online in about 10 minutes ;).

**Comment by Ospeleo** [comment]
dowloader the new beta this morning. It works again. thx
